### ISSUE TITLE
Can't install GitHub Copilot Chat in Codespaces.

### ISSUE THREAD

**Issue by belkacem-co** [microsoft/vscode-copilot-release#103]
- VS Code Version: 1.79.0-insider
- OS Version: macOS Ventura
- Logs: Can't install the release version of 'github.copilot-chat' extension because it has no release version.

Steps to Reproduce:

1. Open a codespace.
2. Click on Install Github Copilot Chat in codespace.

**Comment by QTanweer** [comment]
@belkacem-co, I am still getting this issue, How did you resolve it?

**Comment by belkacem-co** [comment]
@QTanweer I'm not entirely certain, for me it worked properly after reopening the codespace and uninstalling the GitHub Copilot (not the nightly version) which was synced up, try that and see if it resolves your issue.

**Comment by propercroc** [comment]
Same Issue. Tried belkacem-co s solution, but still shows the error.

**Comment by QTanweer** [comment]
I got it fixed. 
As 'GitHub Copilot Chat' extension is still in pre-release stage as of this date, so we need to do these two steps in order to use 'GitHub Copilot Chat' extension inside 'GitHub Codespaces'. 

(First, make sure you have been granted access to the Copilot chat feature from its waiting list...)
In a new codespace:

1. Go to settings icon at bottom left and then click on "Switch to Insiders Version..",  It will ask you to reload the codespace. 
2. Go to the marketplace and search for "GitHub Copilot Chat" extension, and select "Install Pre-release version in Codespaces" from the dropdown menu next to the install option. 

These two steps would not be necessary once they release a "Release" version of Copilot Chat, hopefully.
