### ISSUE TITLE
Context handling is really bad

### ISSUE THREAD

**Issue by vicinik** [microsoft/vscode-copilot-release#1066]
I am working on a React/NextJS project and the context handling of the Copilot Chat is not working as expected. If I include a file with the `#file` macro, it is a gamble if it takes the right file for context. Mostly it just takes the currently opened file. Maybe it is a problem with the naming of the files - in a NextJS project, all pages are named `page.tsx` in different subfolders. Also, referencing multiple files or combining `#selection` and `#file` doesn't work either. Is there any workaround or are there any bugfixes in progress?

This behavior also applies to the Copilot, the inline suggestions are just derived from the file I am currently working on. I think the bevior was much better in December 2023 - at that time the inline suggestions were at least derived from all open tabs, they were brilliant.

- VS Code Version: 1.88.0-insider and 1.87.2
- OS Version: Win 11 Version 23H2
- Github Copilot Version: v1.175.0
- Github Copilot Chat Version: v0.13.1

**Comment by Linjp2002** [comment]
The same as you.

**Comment by roblourens** [comment]
Usually when `#file` is not used, the problem is that the file is large and we weren't able to fit it into our context window. One small improvement is coming in the next release- when a `#file` was actually used, it will appear in the Used References section. This will just help confirm whether it actually made it into the prompt. https://github.com/microsoft/vscode-copilot-release/issues/926

We can also do more to improve how `#file` gets included in the prompt, and I don't think this is tracked in a public issue so I have this now: https://github.com/microsoft/vscode-copilot-release/issues/1083
