### ISSUE TITLE
Works better when treated poorly

### ISSUE THREAD

**Issue by ShawnZuspaet** [microsoft/vscode-copilot-release#1190]
Theres not much to say, I realized that copilot works much better when you treat it like garbage and use rude words when anything doesn't go as expected. Also saying that i am sad or very unhappy with the response sometimes works wonders. Talking to it respectfully often leads to copilot ignoring my requests. Anyone else had that happen?

**Comment by AssiamahS** [comment]
I have noticed this. Giving breaks in multiple task and giving side quests is better. When co-pilot is not working it is most likely due to server overload. How you speak to the chat feature is rarely the reason you got your prompt to execute. As you said, re wording the question can help. Thank you for saying that being unhappy with the answer guides the chat in the better direction. Appreciate it.
