### ISSUE TITLE
Error Code: net::ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by sebastianczech** [microsoft/vscode-copilot-release#1193]
- VS Code Version: 1.89.0 (Universal)
- GitHub Copilot Chat Version: v0.15.0
- OS Version: macOS 14.4.1 
- Logs:
```
Please check your firewall rules and network connection then try again. Error Code: net::ERR_CONNECTION_RESET.
```
Steps to Reproduce:

1. Connect via Global Protect or other VPN
2. Try to use GitHub Copilot Chat and then error `net::ERR_CONNECTION_RESET` appears (in version GitHub Copilot Chat v0.14.0 there is no issue while working via Global Protect or other VPN)

**Comment by alexdima** [comment]
@sebastianczech Did the situation improve now? We have rolled back an experiment where we tried to enable a different network stack for the extension.

**Comment by sebastianczech** [comment]
Yes, after updating to latest versions of extensions, everything works via GlobalProtect. 
Thank you.

**Comment by alexdima** [comment]
Thank you for the prompt answer! Yet, this is still a bit worrying, because it means that there might be a problem with the Electron Fetcher in your environment, which we plan to turn on by default with the next month's release.

Would it please be possible to help us by:
* installing the [latest VS Code Insiders](https://code.visualstudio.com/insiders/). This can be installed side-by-side with your main VS Code installation
* installing the Pre-Release version of the Copilot Chat Extension
* trying if it works under your environment
* if it doesn't work, trying to configure `"github.copilot.advanced": { "debug.useElectronFetcher": false }` and trying if it works then.

Thank you very much!

**Comment by sebastianczech** [comment]
In environment:
- VS Code Insider: 1.90.0-insider (Universal)
- GitHub Copilot : v1.188.867 (pre-release)
- GitHub Copilot Chat : v0.16.2024051001 (pre-release)

I have problems while working via VPN with or without config in `settings.json` (after each change of this settings, I was restarting VS Code Insider):
```json
{
    "github.copilot.advanced": { 
        "debug.useElectronFetcher": false 
    }
}
```

**Comment by alexdima** [comment]
@deepak1556 @chrmarti What further steps can we take to troubleshoot why ElectronFetcher wouldn't work in this environment?

**Comment by devm33** [comment]
Running `GitHub Copilot: Collect Diagnostics` might shed some light if you don't mind @sebastianczech Also if there are any errors in the output panels for `GitHub Copilot` or `GitHub Copilot Chat`. Are inline suggestions from Copilot working for you?

**Comment by deepak1556** [comment]
We also see `ECONNRESET` from Node.js http stack in the above logs, the issue here is independent of the type of fetcher used.
