### ISSUE TITLE
Support Command History with sticky-agents in Copilot Chat

### ISSUE THREAD

**Issue by charris-msft** [microsoft/vscode-copilot-release#1208]
In copilot chat when not chatting with an agent I can press the up arrow to cycle through previous user prompts. However, when I use an agent such as @azure that is sticky, the up arrow doesn't work.

I would love to see the up arrow continue to work with sticky agents. I believe the right behavior is that it should only cycle through user prompts that include the same agent, but I could probaby be convinced otherwise.

**Comment by eleanorjboyd** [comment]
Can verify this works- my one comment is it seems weird that the up arrow would first cause the cursor to jump to the start of the input box then the second up arrow press goes to the previous message. Was this intentional? 

https://github.com/microsoft/vscode-copilot-release/assets/26030610/2fae6958-6d05-45b2-870e-417e2beca955

**Comment by charris-msft** [comment]
I agree with @eleanorjboyd - this felt unnatural to me as well.

**Comment by roblourens** [comment]
This is consistent with some other inputs in vscode but this has also annoyed me and I think I want to tweak it

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/1349 it's not straightforward and there is a question in there, let me know what you think.
