### ISSUE TITLE
[Bug] Copilot adds `"github.copilot.editor.enableAutoCompletions": true` to `settings.json` on every restart

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode-copilot-release#1248]
- VS Code Version: 1.89.1
- OS Version: macOS 14

Steps to Reproduce:

1. Restart vscode.
2. Copilot adds `"github.copilot.editor.enableAutoCompletions": true` to vscode global `settings.json`, which is unnecessary since `true` is the default value.

**Comment by S0yKaf** [comment]
I have the same issue. Very annoying.

**Comment by dleavitt** [comment]
I've set this to `false` because I like to trigger the autocompletions with a hotkey, but now it _turns itself back on_ whenever I open a new project. Was wondering if I was going crazy so glad to see that this is happening to other people.

My temporary solution was to lock my settings.json file so copilot can't change it.

The Copilot extension appears to be closed-source, and the installed extension's source code is minified/obfuscated, so my options for fixing this or figuring out what is going on are pretty limited.

This is a really bad look, guys.

**Comment by S0yKaf** [comment]
My current "workaround" is to add 
```json
"github.copilot.editor.enableAutoCompletions": false
```
  in my projects `.vscode/settings.json` 
  
  But that's far from ideal for various reasons.

**Comment by mor-arusi-riverside** [comment]
I also opened a bug in the github community for it (as I couldn't find this page by googling) https://github.com/orgs/community/discussions/125902

**Comment by jbgraug** [comment]
hotfix: ` code --uninstall-extension github.copilot`

**Comment by Sarke** [comment]
It wants to live!

**Comment by roblourens** [comment]
Sorry for the trouble, sounds like this was due to a bad migration from a deprecated version of that setting. A new version was just released which fixes this.

For future reference, this is the tracker for Copilot Chat issues, you can see completions issues in their community Discussions, and here's one for this issue https://github.com/orgs/community/discussions/125902
