### ISSUE TITLE
Losing chat history in empty windows

### ISSUE THREAD

**Issue by theReynald** [microsoft/vscode-copilot-release#1309]
- Copilot Chat Extension Version: v0.16.1
- VS Code Version: 1.90.1
- OS Version: macOS Sonoma
- Logs:

Watch [video of issue here](https://microsoft-my.sharepoint.com/:v:/p/radolphe/EXn-KZVEEMhBv9jnni9GSMUBnQZ4XMdPqGNgrBW6HyyS9g?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=9yVezR): 

Steps to Reproduce:

1. Open VS Code
2. Click 'Show Chats' button

Image:
<img width="847" alt="Screenshot 2024-06-15 at 1 03 03 PM" src="https://github.com/microsoft/vscode-copilot-release/assets/100732140/14563fbc-a4f9-4df2-9478-ffca3afa58da">

**Comment by roblourens** [comment]
Chats are per-workspace. Do you have previous chats in that workspace?

**Comment by znorris** [comment]
In my opinion, non-workspace chat history needs a home, too.

**Comment by roblourens** [comment]
I see that chats in empty windows don't get saved.

@bpasero I use a workspace-scoped Memento from `getMemento(StorageScope.WORKSPACE, StorageTarget.MACHINE)`. If I close the empty window and open a new one, then I don't get my stored data back. That's probably right for UI state in general, but for something that represents user data, I'd like to keep it around in the next empty window. Is there a way to do that? I could keep it in global storage myself?

It probably gets a little weird when you open multiple empty windows, since they would be overwriting each others' state, but I'm ok with that.

**Comment by roblourens** [comment]
Is there any way to hook into how it works for hot exit, so that having chats in that window would also cause it to use the same workspace identifier and get the chat data back? Or does that not make sense for chat?

**Comment by bpasero** [comment]
You should be able to get that ID via `IWorkspaceContextService.getWorkspace().id`

**Comment by roblourens** [comment]
Thanks. I should probably just keep these chats in global storage, and do my best to merge them between windows.

**Comment by roblourens** [comment]
This can't be perfect, but it should be good enough to avoid losing data in normal cases!

**Comment by Gladskih** [comment]
Is it possible to find a file which contains history of a "chat without workspace"? I ahve just lost a couple of hours of hard work with unexpected history wipe exactly like described above- https://github.com/microsoft/vscode-copilot-release/issues/1309#issuecomment-2226353195
I do not even know English enough to express my frustration.
