### ISSUE TITLE
Continue a previous conversation in copilot chat

### ISSUE THREAD

**Issue by bornik** [microsoft/vscode-copilot-release#1325]
Often I want to refer to one of previous messages but it's quite challenging, I have to explain to copilot two what context I want to return back
Would be great if I can refer/reply to some specific message in chat

**Comment by roblourens** [comment]
Can you explain the scenario some more? It's aware of your history and should be able to understand what you're referencing. An example would help.

**Comment by mykytaborysov-ow** [comment]
Yes I can. 

Objective: Improve user experience in Copilot Chat by allowing better management and navigation of multiple topics within a single chat session.

Current Issue: It is challenging to refer back to previous messages and continue past discussions due to the accumulation of new messages on various topics. Users often have to re-explain the context to continue a conversation.

Proposed Solution: Implement features to:

	1.	Create “separate threads” for different topics within a single chat.
	2.	Start a “new chat” for new discussions from existing message.
	3.	Use a “reply to” function to continue specific conversations without losing context.

Scenario Explanation:

	•	Users often engage in one chat about multiple topics.
	•	With new messages constantly arriving, it’s difficult to manage and refer back to previous discussions.
	•	Example: If a user wants to return to a previous discussion, they currently need to re-explain the context, which is inefficient.

Goal: Provide an intuitive way for users to:

	•	Easily return to previous conversations.
	•	Add more context to discussions.
	•	Seamlessly continue previous conversations without losing the flow.

These enhancements will help maintain context and improve the overall efficiency of communication in Copilot Chat.

**Comment by roblourens** [comment]
Would it help to just be able to switch between previous conversations more easily? Right now you can use the "Show Chats" button at the top of the view to open a previous chat, but we'd like to improve that UX to make it faster and more obvious.

You can also open multiple chats simultaneously in editors.

I think that this kind of workflow is much simpler than trying to come up with UX for "threads" or "reply to this" or something like that, which just seems complicated to me.
