### ISSUE TITLE
Walkthrough's Chat step opens an empty panel

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-copilot-release#1351]
Type: <b>Bug</b>

- Installed Copilot in a fresh stable VS Code
- Installed Copilot
- Didn't sign in, but went to step 3 "Chat with Copilot"
- Clicked "Chat with Copilot"
- 🐛 Panel stays empty, unusable, without sign-in Welcome screen

![Image](https://github.com/user-attachments/assets/f47737a7-b8ff-4c44-86f0-8843b24dcf0f)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 5, 5|
|Memory (System)|64.00GB (37.34GB free)|
|Process Argv|--user-data-dir=/var/folders/cq/2lmpsmc53m500qtgyyrlzhz80000gn/T//cleanvsi/data-14-45-01 --extensions-dir=/var/folders/cq/2lmpsmc53m500qtgyyrlzhz80000gn/T//cleanvsi/ext-14-45-01 --log=trace --log trace --crash-reporter-id 487fc18f-08b0-40a4-87d4-37e92ccd73d5|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bamurtaugh** [comment]
I'm not able to repro. 

- Signed out of GitHub from all extensions (including GitHub Copilot)
- Reloaded VS Code
- Uninstalled GH Copilot extensions
- Reloaded VS Code
- Reinstall GH Copilot extensions
- Don't sign in
- Open GH Copilot walkthrough
- I don't see the `Chat with Copilot` step:
![Image](https://github.com/user-attachments/assets/f6e09a3d-3f32-4fb1-bcc6-e929eeff5076)
- Sign into GH Copilot
- I now get the `Chat with Copilot` step:
![Image](https://github.com/user-attachments/assets/a7f931e0-3503-481e-ad7c-d56296fa55a8)
- Chat Panel opens successfully since I am signed in

**Comment by bhavyaus** [comment]
Unable to repro for me as well. Resolving as won't fix for now.
