### ISSUE TITLE
Add feature for copying chat answers as markdown

### ISSUE THREAD

**Issue by ivanbuzyka** [microsoft/vscode-copilot-release#139]
Currently it is possible to copy text separately (selecting and copying, no formatting (bold, lists) copied etc.) and any code snapshot separately. This however may be useful, especially in "explain me code" scenario to be able to copy as markdown to use it in the documentation etc.

**Comment by dbsxdbsx** [comment]
I vote this. I got this when I said `please refine the doc code in markdown style`. CopilotX does do it correctly, but the output is not copy friendly -- Since there is another markdown punctuations in the feedback, it is impossible to copy the whole answer in raw markdown style.
![image](https://github.com/microsoft/vscode-copilot-release/assets/17372655/7b4ae66b-3343-4c92-abc3-151920916dad)
Look at the above feedback, they are separated incorrectly.

**Comment by HikariWS** [comment]
+1 for this. I was gonna create an issue suggesting it, I'm glad it was alrdy done.

Together with Github Copilot I use Perplexity.ai, they have a `Copy to Clipboard` that formats the text to markdown when copying. This makes documenting much easier, because I can just copy an answer and paste on a md file.

As a reference, I use TheBrain to store knowledge and Typora for viewing and editing md.

**Comment by dbsxdbsx** [comment]
> +1 for this. I was gonna create an issue suggesting it, I'm glad it was alrdy done.
> 
> Together with Github Copilot I use Perplexity.ai, they have a `Copy to Clipboard` that formats the text to markdown when copying. This makes documenting much easier, because I can just copy an answer and paste on a md file.
> 
> As a reference, I use TheBrain to store knowledge and Typora for viewing and editing md.

By the way, currently, I think the answer from Perplexity is smarter than CopilotX.

**Comment by sgbaird** [comment]
A workaround is to ask it to prepend some character or set of characters (e.g., `>>>| `) at the beginning of every line and then remove it ad-hoc. Here's an example:

<img src=https://github.com/microsoft/vscode-copilot-release/assets/45469701/11be68ba-f04b-4495-9d2d-9a657188b70a width=250>

> Regenerate this response, but add `> ` to the start of every single line

<img src="https://github.com/microsoft/vscode-copilot-release/assets/45469701/21266e2c-d7f0-47a5-bfbf-8e1e74f7c039" width=350>

**Comment by roblourens** [comment]
You can right-click > copy to get this
