### ISSUE TITLE
Copilot Is hallucinating all the time

### ISSUE THREAD

**Issue by SiliconSquire** [microsoft/vscode-copilot-release#1407]
Copilot cant go beyond like 100 lines of code if selected it will not be able to see the code
It cant go over 5-10 messages without internally starting over and I have to explain to it the task again 
Too many I can't assist you with that replies
Too many replies that aren't related to the code or question
Using latest version of everything I use it for micro tasks and its not able to perform by a bit its just waste of time to use atm

**Comment by berrutti** [comment]
@SiliconSquire I just came today to this repository to check if I was the only one getting these issues. Unfortunately I can see multiple people having similar problems and no real answers from Microsoft.
 
The quality of the code generation has degraded substantially. 
In the past copilot was able to not only see the open file that I had in my editor, but also to read that file together with another file copy/pasted to the chat. 
With both files it will get all the context it needed to write tests or infer types.
Now, even selecting more than 200 lines is a lost cause. Copilot will fail to return useful errors such as "I cannot read so many lines, please make a smaller selection". 
Instead it will fail silently, either giving you bad suggestions, like very basic scaffolding for tests but not the actual tests, or by saying "I cannot assist you with that". 
It's really infuriating to read copilot gaslighting you with phrases like "As an AI assistant, I cannot do X", when just a second ago it was able to do so. And the only difference being that you selected more lines than what copilot can chew.
I'm seriously considering unsubscribing from this tool, since ChatGPT on its free version can give better suggestion than the model that was actually trained on code.

**Comment by SiliconSquire** [comment]
@berrutti yea i already stopped my subscription its pointless they doing the same exact thing that openAI does when they get overloaded (thats why we dont see system overload errors or any errors anymore on GPT3.5 because they just tweak it down instead with generic replies) or when they reach x amount of expenses they just turn dummyGPT on which GPT 2 can surpass btw, for most users probably

**Comment by rafael-longo** [comment]
I'm having a similar issue, but worse: It just can't handle more than 10-20 lines of code. I selected 23 lines of code and it either says it doesn't have the code or tell me to select a smaller portion. Had it just hallucinating a couple of times as well. It's useless this way. And I just renewed my subscription yesterday. Yesterday it was working fine (I was using it on Android Studio), but today, using in VS Code, it's in this poor state. It's hard to work with such unpredictability. You never know when it's going to be working properly. When it works, it's a very powerful tool, but can't rely on this. Very frustrated...

**Comment by SiliconSquire** [comment]
> I'm having a similar issue, but worse: It just can't handle more than 10-20 lines of code. I selected 23 lines of code and it either says it doesn't have the code or tell me to select a smaller portion. Had it just hallucinating a couple of times as well. It's useless this way. And I just renewed my subscription yesterday. Yesterday it was working fine (I was using it on Android Studio), but today, using in VS Code, it's in this poor state. It's hard to work with such unpredictability. You never know when it's going to be working properly. When it works, it's a very powerful tool, but can't rely on this. Very frustrated...

well VS Code just got update so is Copilot 
:[Copilot uses GPT-4o]- GitHub Copilot Chat upgraded to OpenAI's GPT-4o.:
Let me know if its any better i would appreciate it so i can close this issue

**Comment by berrutti** [comment]
@SiliconSquire For me it's working significantly better. Thanks.

**Comment by SiliconSquire** [comment]
> @SiliconSquire For me it's working significantly better. Thanks.

Yea well I guess copilot team were working silently in the background great to hear that it wasnt 100% intentional just radio silence. i will exhaust the hell out of it with macro micro tasks now 😂
