### ISSUE TITLE
Missing indentation in already indented Python code using "Insert at Cursor" button.

### ISSUE THREAD

**Issue by fahim9778** [microsoft/vscode-copilot-release#151]
- VS Code Version: 1.79.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.19045
- Logs:

Steps to Reproduce:

1. When inserting code suggestions using the `Insert at Cursor` in an already indented code (e.g.: methods inside a Python class), **_it misses the indentation after the function name._**

![Code_-_Insiders_aLD3ftHgcR](https://github.com/microsoft/vscode-copilot-release/assets/26436023/a2c4af34-a925-4783-a5a0-bb9b9d976b80)

**Comment by ulugbekna** [comment]
This should be fixed in latest Copilot Chat pre-release.

**Comment by eleanorjboyd** [comment]
not sure what the desired behavior is here but the indention is not working if your cursor is on a line that already exists (instead of a new line). I would say the original concern is resolved but might be worth exploring the desired behavior here


https://github.com/microsoft/vscode-copilot-release/assets/26030610/9cc51940-3041-49f9-ab3d-92936ee4774b

**Comment by ulugbekna** [comment]
@eleanorjboyd thanks for verifying and feedback! What would you expect instead?

**Comment by eleanorjboyd** [comment]
I think I expected the indentation to still exist even if I placed it on the same line. so it would end up looking like:

```
print("hello") def do_math():
    print()
    print()
```
instead of 
```
print("hello") def do_math():
print()
print()
```

but I think either way is probably fine - this is more a personal opinion.
