### ISSUE TITLE
Please edit the code instead of spilling to chat

### ISSUE THREAD

**Issue by dabrahams** [microsoft/vscode-copilot-release#156]
When I ask for something to be rewritten, just edit my code.  I have version control!

**Comment by daviddossett** [comment]
Have you tried selecting some code an hitting `cmd + i` or `ctrl + i`? You can use copilot inline and ask it to write and edit code, among other things.

**Comment by roblourens** [comment]
We recommend inline chat for editing code

**Comment by dabrahams** [comment]
Seems silly that I should have to discover the magic UI for doing what I want when it could just do what I want all the time, but I guess you all know why you don't want to provide that.

**Comment by roblourens** [comment]
We have some work in progress to give a better experience when you want to apply suggestions from the chat view to the editor. But I believe that editing a file automatically from a query in the chat sidebar would be pretty unexpected, and that a chat conversation is not the right UI paradigm for that task. It's hard to know that was your intent, and which file you want edited, etc. We've added a bunch of new entrypoints to inline chat recently since it's been hard to discover. Lmk if you have any other suggestions.

**Comment by dabrahams** [comment]
Thanks. If you had just said, “we're not gonna do this” I would have left this issue alone, but you justifying that choice with arguments that don't make any sense to me.  For example:

> editing a file automatically from a query in the chat sidebar would be pretty unexpected

When my query explicitly asks copilot to edit the file, that's _exactly_ what I expect to happen.  Thus this bug report.

> a chat conversation is not the right UI paradigm for that task

That's a value judgement you are free to make, but the fact remains that people will try it.  “Hard to know the intent” seems par for the course with AI, but in this case the specific query was a request to change the highlighted code in the editor; seems to me which file to edit is obvious. Of course there may be implementation factors that make this hard, but the fact that copilot spits out a bunch of code in chat that I have to copy and paste back into the highlighted region seems utterly silly _from a user point of view_.
