### ISSUE TITLE
Issue with Copying Selected Text in GitHub Copilot Chat Extension

### ISSUE THREAD

**Issue by albert-zilberman** [microsoft/vscode-copilot-release#1616]
When using the GitHub Copilot Chat Extension in Visual Studio Code, I am experiencing an issue where copying selected text often results in copying the entire response instead of just the selected fragment.

- Copilot Chat Extension Version: v0.20.3
- VS Code Version: 1.93.1
- OS Version: Windows 10 Pro, 22H2
- Logs:

Steps to Reproduce:

1. Open the GitHub Copilot Chat Extension in Visual Studio Code.
2. Select a specific fragment of text from the response.
3. Press Ctrl+C or right-click and select "Copy".
4. Paste the copied text into a text editor.

Expected Behavior: Only the selected fragment of text should be copied.

Actual Behavior: The entire response is copied instead of just the selected fragment.

**Comment by roblourens** [comment]
The Copy context menu always copys the full response https://github.com/microsoft/vscode-copilot-release/issues/416

**Comment by decentraliser** [comment]
Hi! This issue was not solved @roblourens

What users expect is that when you select a subset of a code block in the Copilot chat, and press ctrl+v, this subset will be copied.
When copying text from Copilot messages that are outside of code blocks, it copies as expected.
Copying only from the copy all button is not optimal because most of the time it does not fit users needs, even if it might be the end goal

keep up the good work <3 !
