### ISSUE TITLE
Give current scroll location context to Copilot Chat

### ISSUE THREAD

**Issue by odedsolutions** [microsoft/vscode-copilot-release#162]
If I scrolled to the middle of a file, and asked the chat "make this code more efficient" - I expected it to make the code currently visible more efficient, but it just started at the top of the file.

Providing the chat window, the code in the current window, or the scroll position within the file, should provide helpful context

**Comment by odedsolutions** [comment]
Should note I'm in a jupyter notebook environment

**Comment by culstrup** [comment]
I'd like to echo this by saying that in general it's unclear to me what copilot chat is "looking at" when I'm talking to it.

Is it able to see errors thrown in my command line interface? Is it looking at the part of a script that I'm focused on? Can it see how different files are arranged in the directory that I have open?

I guess my assumption would be that it can see everything that I can see. And then of course the cherry on top would be for it to have the context of everything in the entire project available either within the context window or retrieval via retrieval augmented generation.

Anyway, it's unclear to me what additional context it even has when I submit a chat message, which makes me hesitant to use it because I'm not sure if I should be highlighting something or copying-and-pasting text, and it would be really nice to be able to know.

**Comment by roblourens** [comment]
This is improved a bit since the issue was filed, but will be a focus in January as well

https://github.com/microsoft/vscode-copilot-release/issues/675
