### ISSUE TITLE
Why the context and code text count is very small for copilot chat?

### ISSUE THREAD

**Issue by faheemstepsharp** [microsoft/vscode-copilot-release#1665]
Please tell us why it's very low also when will we see improvements and have claude level context?

**Comment by ilund** [comment]
I would very much like to know this as well. What is the point of having a chat history and being able to add multiple files to the context if it is all forgotten almost immediately on the next chat because it can't store the context from the previous messages in the history. It makes copilot chat almost unusable.

**Comment by lramos15** [comment]
Please provide concrete examples we can operate on where the context is not allowing you to complete the work you need. The context window is actually quite large, we just do not advertise it at this time.
