### ISSUE TITLE
worthless answers

### ISSUE THREAD

**Issue by knightofknee** [microsoft/vscode-copilot-release#1669]
it keeps repeating the same failed solution even if i show that i already implemented it. this is worthless and it seems especially bad compared to regular chatgpt. like it has an ego and an inability to acknowledge its own failures. please drop the ego. (screenshot is of a bonus: reporting this issue was too much data for github apparently? weird)
![Screenshot 2024-09-27 at 10 12 48 PM](https://github.com/user-attachments/assets/b59269fd-8216-46ec-98de-6e1810f77a45)

**Comment by kupietools** [comment]
Ditto. The endless going circles with it insisting on repeating the same mistakes I've already told it to stop doing is a tremendous waste of time. It cycles between three or four wrong answers, always forgetting by the third question following what I've already told it repeatedly is wrong and not to do. 

This is far beyong this just having some rough edges that need sanding off. This going in endless circles is a 100% waste of user time, absolutely and totally nonconstructive. 

And I can't even get it to submit the chat that I wanted to submit feedback about at all. It just opens this issues section in my browser. There's no way for me to export, save, copy, or otherwise indicate the chat that the problm is with.

**Comment by faheemstepsharp** [comment]
+1 happens to me sometimes

**Comment by roblourens** [comment]
Sorry for the bad experience but something more concrete would help me improve those scenarios. Please share the specific prompts or just share the whole conversation (right click > copy all). You can also email it to me if you prefere.
