### ISSUE TITLE
UI is suddenly non-standard and hard to use

### ISSUE THREAD

**Issue by jeffcovey** [microsoft/vscode-copilot-release#2142]
When I opened Visual Studio Code this morning, the Copilot Chat icon was gone from the side toolbar where it appeared with Explorer, Source Control, etc. I could only find it in a tiny icon next to the search field. That opened it on the opposite side from all other extensions. It doesn’t take their place when I switch to it (the Navigator window doesn’t become a Copilot window), but creates its own window and shrinks my editor window to invisibility. I can’t toggle its visibility with cmd-b like I do with any other extension. I haven’t found any hotkey to close it, I have to leave the keyboard and drive my pointer to a tiny “x”.

Is this a mistake, or just an experiment? I hope it’s gone soon.

**Comment by tim-mukhin** [comment]
+1 
reported the same issue, but mine is even worse: my top pane is hidden, so I don't see the new copilot icon at all
#2167

**Comment by bpasero** [comment]
You can move views around, including back to the primary sidebar: https://github.com/microsoft/vscode-copilot-release/issues/2062#issuecomment-2449241868

Keybinding to toggle secondary sidebar: `Ctrl/Cmd+Alt+B`

**Comment by jeffcovey** [comment]
> You can move views around, including back to the primary sidebar

As I reported on that ticket, that doesn’t work on my copy of VS Code.

Can the Copilot extension simply stop doing this and go back to the way it was? I don’t see any advantage to this change, and I haven’t seen anything but complaints and confusion about it.

**Comment by bpasero** [comment]
@jeffcovey we need to look into that issue and resolve it, but in the meantime, the view can be moved back also using the "Move View" command:

![Image](https://github.com/user-attachments/assets/e0f94d07-11d5-4d37-ac25-6f98097e1064)

**Comment by jeffcovey** [comment]
> we need to look into that issue with drag and drop not working and resolve it

Sure. But in the meantime, can’t someone just put things back the way they were? All you have to do is stop fixing what wasn’t broken.

**Comment by bpasero** [comment]
The secondary side bar is the default location for Chat and Copilot Edits since our November release. There are ways to move these views to side bar or panel as needed. 

If you see usability issues with the secondary sidebar, please report them as issues to https://github.com/microsoft/vscode/issues and we are happy to take it from there. Our plan is to make the secondary sidebar easier to use and better. It is also the first time for us to ship a view there by default, so we are happy to learn how to improve that.

I am going ahead and close this issue 🙏
