### ISSUE TITLE
Copilot is Overly Eager to Provide Code

### ISSUE THREAD

**Issue by namse** [microsoft/vscode-copilot-release#2465]
I want to use Copilot to discuss my algorithms and approaches to problem-solving in programming, rather than focusing on the actual code. However, it constantly pushes implementation code on me, even when I'm just looking for guidance on the approach. I’m tired of having to preface every question with “Don’t write any code!” to try to steer it in the right direction.

I’m looking for a way to calm down Copilot's persistent urge to generate code so I can get advice on strategy without it taking over with lines of code.

**Comment by asuccurro** [comment]
have same issue, and when pointing to specific errors it keeps re-suggesting the same code over and over again

**Comment by jrieken** [comment]
>  I’m tired of having to preface every question with “Don’t write any code!” to try to steer it in the right direction.

You can use custom instructions for that https://code.visualstudio.com/docs/copilot/copilot-customization



> I want to use Copilot to discuss

How do you interact with copilot? Via panel chat, edits, or inline chat? Each of them has a different bias how it will answer

**Comment by jrieken** [comment]
missing information

**Comment by willie84dutoit** [comment]
Sorry, I am experiencing the same issue, and @jrieken pasting a link is not really good enough, if you cannot help by interpreting the link you posted, keep it to yourself.

...o... my apologies, but this is frustrating, and I follow the instruction of the link, those instruction work for Copilot chat, I found, not edits. And since Edits and Chat is disconnected, you choose one to work with.
