### ISSUE TITLE
Shortcuts to insert code contents from Chat interface

### ISSUE THREAD

**Issue by efesurekli** [microsoft/vscode-copilot-release#274]
Would be great to have the "insert at cursor location" button shortcut so that I don't have to switch to mouse to copy the code generated by the copilot chat.

**Comment by roblourens** [comment]
Suggestions for a shortcut that makes sense? You can also assign your own keybinding to the command `workbench.action.chat.insertCodeBlock`

You can focus a codeblock with F9 then use your keybinding

**Comment by efesurekli** [comment]
Thanks! I'll assign one for now. For shortcut, maybe a rememberable short combo such as Command+K then V can be useful, seems also un-assigned.

**Comment by janosh** [comment]
This is not working for me:

```json5
  {
    "key": "cmd+enter",
    "command": "workbench.action.chat.insertCodeBlock"
    // "when": "copilot.activated"
  }
```

![Screenshot 2023-08-20 at 1 36 10 PM](https://github.com/microsoft/vscode-copilot-release/assets/30958850/632dae38-bc8c-4e4d-9c86-059affe51c5b)

The UI shows the shortcut as active and F9 to highlight the code suggestion works. But cmd+enter does nothing.

**Comment by Thomas-McKanna** [comment]
I agree that some way of more easily inserting code suggestions would bring Copilot Chat to the next level. Ideally, this insertion would optionally be automated.

Here is the use case I'm thinking about:

1. You try to run code but there is an error or it is not behaving how you expect.
2. You highlight code and paste error message or what you want to be different in the Copilot prompt.
3. Copilot returns a response containing a new version of part or all of the code.
4. (this is the new part) Copilot automatically inserts/replaces the code in the affected file.

As I work on code, I'm doing step 4 manually, potentially many times in a row as I iterate on the code. But I don't see any reason why this step couldn't be automated. It would save so much time and remove a tedious step.

**Comment by roblourens** [comment]
@janosh This actually worked for me- most likely you have some other keybinding taking precedence. You can troubleshoot it with the command "Toggle keyboard shortcuts troubleshooting"

**Comment by roblourens** [comment]
@Thomas-McKanna agreed, right now the inline chat experience (cmd+i instead of the panel chat) is a better solution for this

**Comment by d-mahard** [comment]
I think this is the same feature but I would like to provide more info/suggestion, and besides, the F9 did not work for me:

v1.85.0 on Windows 11

### I want to achieve the following workflow with only keyboard.

1. While am in editor, I would like to ask copilot a question. I can do that by binding key to `workbench.panel.chat.view.copilot.focus`
2. My cursor focus jumps to the chat inbox (inside side bar) I then write the question, then copilot provides an answer
3. I want to copy the code suggested in the _codeblock inside the answer_, which I can use `workbench.action.chat.insertCodeBlock`. _**Problem is I cannot jump focus to the code block itself**_. (`f9` as suggested above did not work for me. I tried to troubleshoot using the shortcut troubleshooting tool as well)

### The best I can already do is the following:
1. while the focus is in the chat input box, I can press `Ctrl+Up`, to move the focus to the answer box (which contain the code block)
2. press `Tab` for about 4 times, until I reach the codeblock. (it will jump to the thumbs etc first before reaching the code block)

### Suggestion

at least for the side bar, using `Ctrl+Up/Down`  is pretty common, so I think it is  sufficient to just additionally provide the jump from the answer box to the code block. Using `Ctrl+Right` to jump to the code block, and `Ctrl+Left` to focus back to answer box might be a good idea. 
When there are multiple code blocks in an answer box, when the focus is in a code block, `ctrl+up` or `ctrl+down` arrow should be sufficient to move between them (because `up` and `down` without `ctrl` will move the cursor within that code block).

See below. The blue box is what I called the answer box, which is on focus.
![image](https://github.com/microsoft/vscode-copilot-release/assets/146386738/c28ffe56-c482-4095-b87d-c06386ce3ec5)

**Comment by d-mahard** [comment]
> Suggestions for a shortcut that makes sense? You can also assign your own keybinding to the command `workbench.action.chat.insertCodeBlock`
> 
> You can focus a codeblock with F9 then use your keybinding

btw @roblourens  what command is supposed to be called by the `F9`?

**Comment by roblourens** [comment]
`workbench.action.chat.nextCodeBlock`

**Comment by d-mahard** [comment]
Thank you! Apparently I have different default for that command. Not quite sure why though..

![image](https://github.com/microsoft/vscode-copilot-release/assets/146386738/5c0a0074-3980-4158-bed6-59a6d9bf2db3)

**Comment by roblourens** [comment]
Oh sorry, maybe it's different on Windows

**Comment by isidorn** [comment]
These keybindings are configurable, so closing this as done.
