### ISSUE TITLE
죄송합니다. 책임 있는 AI 서비스에서 응답을 필터링했습니다. 프롬프트를 바꿔 입력하고 다시 시도하세요. 자세한 정보.

### ISSUE THREAD

**Issue by psh667** [microsoft/vscode-copilot-release#2885]
Type: <b>Bug</b>

죄송합니다. 책임 있는 AI 서비스에서 응답을 필터링했습니다. 프롬프트를 바꿔 입력하고 다시 시도하세요. 자세한 정보.

위와 같은 응답이 계속 나옴

Extension version: 0.22.4
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Linux x64 5.15.0-126-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.17GB (9.46GB free)|
|Process Argv|--crash-reporter-id 31293c93-269c-4fa0-84d4-287898b90c6c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by lukehemmin** [comment]
I am also experiencing the same issue repeatedly. I am a user who asks questions in Korean and receives answers in Korean. When I ask about code or engage in chats to write code, I keep encountering the same problem as the original poster mentioned. After pressing the retry button about five times, I finally get an answer.

This issue is truly frustrating. At some point, due to the implementation of stricter limitations on prompts (though I can't confirm if this is related to questions in other languages), problems have arisen where responses are either refused or cannot be provided when questions are asked in other languages. These restrictions have been consistently causing issues. This problem completely disrupts the experience of users who use other languages. I sincerely hope it gets resolved as soon as possible.
