### ISSUE TITLE
Add a read aloud feature!!!?

### ISSUE THREAD

**Issue by erionmesicpw** [microsoft/vscode-copilot-release#313]
Would you please add a way to read aloud selected text on Copilot Chat, in a right click options?
Thank you!

**Comment by meganrogge** [comment]
If you turn on screen reader optimized mode, that will happen automatically!

**Comment by meganrogge** [comment]
Could you provide more info abt what you would want to select and your use case?

**Comment by Geek-ySeeker** [comment]
As a modest linguist, I am asking for info. in various languages, to perpetually broaden my vocabulary quickly.  Having the Outlook 365 'Read Aloud' functionality would be very useful.  It would also help those who are blind and use 'Jaws'.  Also, for those with better audial (rather than eidetic) memory, it would be an excellent improvement.

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/196261
