### ISSUE TITLE
Slow responses as the length of the chat history increases

### ISSUE THREAD

**Issue by hussenmi** [microsoft/vscode-copilot-release#34]
Copilot chat seems to respond fast in the beginning but as the length of the chat history increases, it gets slow and even stops responding. I have to clear the chat and start again to make it start working again.

**Comment by digitarald** [comment]
@hussenmi it is slow to start, or also slow to stream in?

**Comment by lramos15** [comment]
Closing due to lack of followup and unable to repro.

It is expected that the LLM will slow down somewhat as it accepts more context and has to reason about it, but it should not be significant to the point you feel like you need to clear your chat. Please open a new issue if this is still negatively impacting you.
