### ISSUE TITLE
Copilot Chat does not have any context of directory structure of an existing application

### ISSUE THREAD

**Issue by leeparayno** [microsoft/vscode-copilot-release#354]
For example for a Flutter application, with some defined directory structures for front end model object code, for screens, for UI components--Copilot Chat does not have any context of what the existing directories are and what existing code might already exist.

To add new model objects, Copilot does not take the existing standards of the existing model object code when creating the new code output.

Not taking into account existing code, Copilot Chat can start with incorrect model code, and then screen UI code will also be based on the incorrect model properties, creating subsequent incorrect UI entries with wrong UI controls.

**Comment by Markussss** [comment]
I came here to say almost the same.

I am working on a Typescript project. The first thing I asked Copilot Chat to do was to generate a return type for a function. I only gave it the name of the function and expected that it would have all the necessary context in order to do so. The proper return type looked something like `interface RelatedLocationIds { flexibleLocationIds: number[], locationIds: number[] }`, but Copilot Chat generated this:

```typescript
interface Location {
  name: string;
  address: string;
}

interface RelatedLocations {
  [key: string]: Location[];
}
```

Problems:
1. `RelatedLocations` and `Location` are already known and used types in our codebase
2. The type or interface _can not_ have just any string as the key in this case, and it would be evident in looking at where the this function is used
3. We are not returning an object containing arrays of Locations, but an object containing arrays of numbers

**Comment by d-mahard** [comment]
Another use case where providing dir structure to copilot will be useful:

When diagnosing problem related to filepath. For example, I have a dockerfile with a copy command that is actually incorrect. I asked copilot but could not give correct solution. Then I experimented by giving it the structure of my dir manually using [this extension](https://marketplace.visualstudio.com/items?itemName=Shinotatwu-DS.file-tree-generator).

Then the diagnosis gets slightly more accurate. (besides grammatical error, the proposed solution is also still incorrect, but the clue given is spot-on)
![image](https://github.com/microsoft/vscode-copilot-release/assets/146386738/7e35b444-e9f5-4626-888a-e91d5b68365a)

**Comment by mjbvz** [comment]
You can now use `@workspace` to provide copilot with relevant workspace information when asking questions: https://code.visualstudio.com/docs/editor/github-copilot#_agents-and-slash-commands
