### ISSUE TITLE
Copilot Chat doesn't work with remote VS Code server

### ISSUE THREAD

**Issue by rrmistry** [microsoft/vscode-copilot-release#39]
Bringing this here from https://github.com/microsoft/vscode-copilot-release/issues/9#issuecomment-1553220352

_____

# EDIT: Workaround Confirmed ✅

Execute this in your remote VS Code server environment (Dev Container / SSH Tunnel):

```bash
code-insiders --install-extension github.copilot-chat@prerelease
```

Keeping this issue open until issue is remediated without work-around.

This means either:

1. CoPilot Chat extension released in main VS Code
OR
2. VS Code Insiders uses insider's code server

Kudos to @pkerschbaum for workaround:
https://github.com/orgs/community/discussions/55019#discussioncomment-5890825

_____

# Issue Description

As of today, it still doesn't work. But the error is as follows:

<img width="1197" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/25514145/23979a5a-6ab0-45b9-9308-b98ebc450aec">

```
2023-05-18 15:12:48.615 [error] Failed to install extension. github.copilot-chat
2023-05-18 15:12:48.615 [error] ReleaseVersionNotFound: Can't install release version of 'github.copilot-chat' extension because it has no release version.
    at e.ExtensionManagementService.G (/root/.vscode-server-insiders/bin/9084e081d4e89ed8ab67fce340d573c4e1378939/out/vs/server/node/server.main.js:142:32025)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async e.ExtensionManagementService.installFromGallery (/root/.vscode-server-insiders/bin/9084e081d4e89ed8ab67fce340d573c4e1378939/out/vs/server/node/server.main.js:142:23678)
```

It seems that VS Code Insider's remote server installs a Code-Server version that doesn't allow the Copilot Chat extension's version.

This could be a [VS-Code-Server](https://github.com/microsoft/vscode) issue.

The same works well without issues when installed in VS Code Insiders locally.
_____

### VS Code Insider's build details:

Version: 1.79.0-insider
Commit: 9084e081d4e89ed8ab67fce340d573c4e1378939
Date: 2023-05-15T05:24:19.845Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0

**Comment by rrmistry** [comment]
For our use case, we use Okteto to spin up a dev container on Kubernetes and connect via SSH.

Then use VS Code's Remote Explorer extension to connect a new VS Code remote Instance over SSH.

In our specific use case, we are seeing this issue but haven't checked other SSH scenarios.

**Comment by cajewsa** [comment]
I am experiencing the same issues.

**Comment by Bailey-24** [comment]
using docker, meet the same problem

**Comment by Meathelix1** [comment]
+1 I work a lot in WSL2 and would love for this to work in it.

**Comment by Kaloszer** [comment]
Same WSL Ubuntu, running insiders.

**Comment by mattwelke** [comment]
I seem to be affected by this too. I'm getting started now that I've received the email telling me I've been invited to the GitHub Copilot chat private beta:

> For Visual Studio Code:
>    Download and install [Visual Studio Code - Insiders](https://code.visualstudio.com/insiders/)
>    Already on the Insiders build? Make sure you are on the latest version!
>    In VS Code Insiders, go to the Extensions tab (Cmd+Shift+X) in the activity panel and search for and install the [GitHub Copilot Nightly extension](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-nightly).
>    If you have not previously authorized VS Code Insiders in your GitHub account, follow the steps to do so, you will be prompted to sign in.
>    A new Chat icon appears in the activity panel. Click on it to see the conversation interface.
>    If that doesn't work, restart the editor and authorize GitHub Copilot to see the chat window.

The chat button appears on the left side of my screen when I'm using VS Code without being connected to WSL.

![image](https://github.com/microsoft/vscode-copilot-release/assets/7719209/f3ceb5b0-ff8d-4839-abb4-e518b68439a4)

But when I've opened a folder in WSL, it doesn't appear.

![image](https://github.com/microsoft/vscode-copilot-release/assets/7719209/0955d51c-24fd-425c-8fd1-d3725dcefb1a)

But this isn't useful for me. I don't do any develop on the Windows side of my OS. I use Windows as an interface into an Ubuntu WSL installation where I do development. I have an Ubuntu dual boot setup so I can switch to that to try this out, but that's inconvenient because I like to remain in Windows for access to Linux software development tools and Windows programs at the same time.

**Comment by Kaloszer** [comment]
@mattwelke - found a fix yesterday
https://github.com/orgs/community/discussions/55019#discussioncomment-5890825
code-insiders --install-extension github.copilot-chat@prerelease inside of WSL env, restart vscode then and it should pop up (I also had to disable>enable it again)

**Comment by bamurtaugh** [comment]
Thanks all for describing this issue, and I'm sorry to hear you're having trouble!

With the latest VS Code Insiders, Copilot Nightly and Copilot Chat Nightly, and remote extensions, I'm able to successfully use chat in remote environments like WSL. I did need to specifically open the Extensions View and click the option to install the chat extension in my remote environment.

![image](https://github.com/microsoft/vscode-copilot-release/assets/25310137/4b7857a3-91b5-4008-bf82-92d655176590)

Are folks still experiencing this issue with all of the latest versions of the tools I mention? What happens if you try to install chat in the remote environment? Does the fix @Kaloszer mentions help?

**Comment by rrmistry** [comment]
As of the below version, I can confirm that VS Code Insiders now works well in allowing to install Copilot Chat extension without needing any workarounds.

```
Version: 1.79.0-insider
Commit: f6be5461f8bc69013a605f5baea834651c6589fb
Date: 2023-05-20T01:21:14.154Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

This could be closed if a few others could confirm as well.

**Comment by mattwelke** [comment]
I'm planning to play around with this at some point over the next few days. It would be a Win 11 + WSL 2 w/ Ubuntu 20.04 a test.

**Comment by mattwelke** [comment]
Sorry for replying back so late.

For me, this is working now. I re-opened VS Code Insiders, looked at my installed extensions, and noted that I already had the "GitHub Copilot" and "GitHub Copilot Chat" extensions installed. Also, I was on the prerelease track for them.

![image](https://github.com/microsoft/vscode-copilot-release/assets/7719209/8486e99a-14dc-4b03-a66c-3280c3ce54f7)
![image](https://github.com/microsoft/vscode-copilot-release/assets/7719209/358a689f-e66e-44e4-85c6-1c2a4e5ed705)

I restarted VS Code Insiders to allow it to get the latest update, so that when that was finished, all three of these components would be the latest version (as stated by @bamurtaugh to be required for this to work). When it finished restarting, I noticed that there was a chat tab open.

![image](https://github.com/microsoft/vscode-copilot-release/assets/7719209/9878f73e-4250-4d64-8ddc-8a5307ce45c0)

And it seems to work!

![image](https://github.com/microsoft/vscode-copilot-release/assets/7719209/b362acea-cf3a-4431-824c-bc846dc3fa1e)
![image](https://github.com/microsoft/vscode-copilot-release/assets/7719209/fa79fb96-ace5-4809-b06e-0120e553a15c)

So this doesn't mean I've tested how effective Copilot Chat is, but now I've got everything wired up with my WSL environment so that I can begin evaluating it.
