### ISSUE TITLE
Cannot copy generated text when vs code notebook also open

### ISSUE THREAD

**Issue by willeppy** [microsoft/vscode-copilot-release#458]
## Issue
If I try to copy and paste the text generated by copilot chat AND also have a vs code notebook open, the content of my currently selected cell is copied rather than the copilot text. This behavior does not happen when a normal file is open (seemingly only notebooks). The copy also works fine for generated code blocks by copilot that get presented as code.

## Version
- VS Code Version: 1.84.0 (commit 7d4027b62bb1e620e5454580450fa646682bc102)
- OS Version: MacOS Ventura 13.5.2
- Logs: N/A

## Steps to Reproduce:

1. Open up copilot chat and a vs code notebook
2. Ask a question and try to copy text that is not code (highlight and command C)
3. When pasting back in the notebook, will be the content of whatever the currently selected cell was

Screenshot:
<img width="796" alt="Screenshot 2023-10-06 at 1 01 56 AM" src="https://github.com/microsoft/vscode-copilot-release/assets/13400543/e385d832-720a-42be-9501-2037d60e3970">

When I hit command C, the text `print("hello world")` is copied rather than the actual text I have highlighted. Interestingly, the copy works fine if i try to copy the code part `x = 5`.

**Comment by roblourens** [comment]
Yeah this isn't working quite correctly: https://github.com/microsoft/vscode-copilot-release/issues/416

Although maybe also looks like a notebook context key might be incorrectly turned on? @rebornix

**Comment by m3h0w** [comment]
The problem with copying into the Jupyter Notebook instead of into Copilot or with copying into the Notebook instead of from Copilot is related to how the Notebook handles copying entire cells.

There is a simple workaround you can use: make sure that you have another file opened side-by-side with the Notebook and whenever you want to paste something to Copilot or into the Notebook, make sure you focus (click on) a non-notebook file first. Then things work as expected.
