### ISSUE TITLE
"Fix/Explain using copilot" always takes priority over other extensions

### ISSUE THREAD

**Issue by griffi-gh** [microsoft/vscode-copilot-release#482]
- VS Code Version: 1.83.0
- OS Version: Win11H
- Logs: N/A

Steps to Reproduce:

1. Press Ctrl+. for quickfix
2. Copilot Chat "Fix" is now the default option, which is not the expected behaviour by most developers.  
    - Quick Fix options provided by LSP are usually better/more useful than generic Copilot ones 
    - Muscle memory: I 'm used to tapping Ctrl+. -> Enter for filling match arms, which is no longer the case with the Copilot Chat extension installed  
    - ("Fix using copilot" is useless for most languages other than JS/TS at the moment anyway)

![Code_fhx4FKLBJw](https://github.com/microsoft/vscode-copilot-release/assets/45996170/a21f69e7-74b5-434a-99ec-9d19d7db8b37)

**Comment by aiday-mar** [comment]
Hi thank you for filing the issue. In the next update of VS Code stable 1.84 this issue should be fixed. Let me know if you continue seeing this error.

**Comment by eric-gardyn** [comment]
still seeing the issue

**Comment by aiday-mar** [comment]
Hi @eric-gardyn thank you for commenting. Could you please include here a copy paste of the information you see under `About Visual Studio Code` and also include a screen shot of the quick fix menu with the code actions showing the error. Could you please also describe what you would expect to see?

**Comment by davidmelvin** [comment]
I have a similar issue but the behavior is different than I expected. I get different Quick Fix menu items if my cursor is in the middle of a variable name vs. at the start or end of the variable name.

Cursor at end works fine and shows the LSP quick fix I want:
<img width="743" alt="Screenshot 2024-01-11 at 10 14 22 AM" src="https://github.com/microsoft/vscode-copilot-release/assets/3642040/e25b1ed7-7c3d-477b-b36f-c5bee9058c9a">

Cursor in middle only shows GitHub Copilot quick fix which I don't want:
<img width="746" alt="Screenshot 2024-01-11 at 10 11 45 AM" src="https://github.com/microsoft/vscode-copilot-release/assets/3642040/b27de254-8bb6-44fd-a227-b8932bb9931e">

Is this expected behavior? I don't remember my cursor position mattering before I installed Copilot.

```
Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:16.874Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.2.0
```

Thanks for your help and let me know if there is any additional info I can provide!

**Comment by aiday-mar** [comment]
Hi @davidmelvin thank you for posting about this issue. I believe here that presumably the TypeScript server is returning code actions only at the end of the word as you said. It could also be that this code action is provided by another extension (not inbuilt one) in which case the issue should be filed to the extension authors.

Pinging @mjbvz for this

**Comment by davidmelvin** [comment]
Ah, I see. Thanks!
