### ISSUE TITLE
Option to disable GitHub Copilot Chat

### ISSUE THREAD

**Issue by jsulopzs** [microsoft/vscode-copilot-release#510]
I am working with suggestions inline and every time I press `ctrl + i`, the github copilot chat appears. I've tried to dissable it, but I don't find the option anywhere.

If I disable the chat extension, the copilot will also be disabled.

Could you please make the option to disable only the chat?

**Comment by LogicDaemon** [comment]
I have a related problem: https://github.com/microsoft/vscode-copilot-release/issues/698
and currently I'm using a quite a weird workaround to disable Chat without disabling Copilot in general.

Having a more civil way to do it would be great.

**Comment by roblourens** [comment]
I agree re:removing the keybinding

**Comment by StuartBertram** [comment]
I don't know how many of the key bindings I _actually_ needed to remove. But I've just removed about 40 chat-related key bindings.

If the only way to remove this is to disable the key bindings, why is it a separate extension? I understand that it might be architected so that you can't have the chat add-on without the core auto-complete functionality, but requiring both seems unnecessary.
