### ISSUE TITLE
FEAT: Add a Clear Chat Button to Copilot Chat Panel

### ISSUE THREAD

**Issue by asilverman** [microsoft/vscode-copilot-release#749]
## Description

I propose adding a new button within the Copilot Chat extension panel in VSCode that mimics the `/clear` command functionality. This button would allow users to quickly and easily clear the chat history, enhancing the user experience. The design of this button could be similar to the 'Clear Output' button found in the VSCode Debug panel, ensuring consistency and familiarity for users. See image below:

![image](https://github.com/microsoft/vscode-copilot-release/assets/9611108/13b6e609-d64b-4c2c-8265-7774213997ec)
![image](https://github.com/microsoft/vscode-copilot-release/assets/9611108/b22e8647-bf04-4e13-a3b9-73f3fc173845)

**Benefits**
This feature would improve the usability of the Copilot Chat by making it easier for users to manage their chat space, especially in long coding sessions. It aligns with VSCode's existing design principles and enhances the overall efficiency of the tool.

**Comment by lramos15** [comment]
It's the plus icon. It starts a new session which is the same as clearing the existing one 
<img width="110" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/4544166/81516425-e8da-4fcd-a2bf-571f70adafed">

**Comment by asilverman** [comment]
> It's the plus icon. It starts a new session which is the same as clearing the existing one <img alt="image" width="110" src="https://private-user-images.githubusercontent.com/4544166/296369658-81516425-e8da-4fcd-a2bf-571f70adafed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwOTg4MzAsIm5iZiI6MTcwNTA5ODUzMCwicGF0aCI6Ii80NTQ0MTY2LzI5NjM2OTY1OC04MTUxNjQyNS1lOGRhLTRmY2QtYTJiZi01NzFmNzBhZGFmZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTJUMjIyODUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGZmZmFkZGZlY2JlODE3MGFlOTY1Zjg0YTUzZWY4NjIyZTMyZmI2OGZjOGM3MzA1ZTY2ZGQ0ZGRhYzkyMDZiNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.j7WjP1MRxBIxG6oa2NXkmIH4uiYc_t1CYDNk_JMrxFM">

while that may be true that it starts a new session, it is not the same since the old session is left to linger.

**Comment by bamurtaugh** [comment]
Thanks for filing @asilverman and for the initial thoughts and help here @lramos15. 

It seems to me there are a couple parts to this request:
1. Making it clearer to users how they can clear their session 
     * But "clear" can have a few definitions here (just clearing out the chat panel? totally wiping out chat history / previous sessions?), which brings me to...
2. Adding the ability to clear all past chat history with one click

**For part 1:**
I wonder if something even like slightly more detailed tooltip text could help users getting started here - i.e. `Clear and Start New Session` rather than just `New Session`:

![image](https://github.com/microsoft/vscode-copilot-release/assets/25310137/cad3a873-dd32-45b0-b063-6f4fbe14329c)

**For part 2:**
> since the old session is left to linger and results in my VSCode instance consuming memory and other resources

My understanding is the behavior @asilverman is seeking here might actually be a new feature we don't have today. Right now, users can `x` to clear out individual previous chat sessions, but I don't think we have a button to clear all history?

![image](https://github.com/microsoft/vscode-copilot-release/assets/25310137/dc5de843-01ff-435e-9513-0e4f3b2981b6)

For fuller clarification/comparison: the `/clear` slash command will start a fresh session by cleaning out the chat panel, but that session will still appear in chat history.

@lramos15 what do you think?
