### ISSUE TITLE
Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by alvinycheung** [microsoft/vscode-copilot-release#761]
- VS Code Version: Visual Studio Code Insiders
Version: 1.86.0-insider (Universal)
Commit: 0b571a26e213bf1ec6266e37152ced80c006bd1e
Date: 2024-01-18T05:37:28.553Z (1 day ago)
Electron: 27.2.1
ElectronBuildId: 26149897
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 22.4.0
- OS Version: macOS Ventura 13.3.1 (a)
- Logs:
```
2024-01-19 08:57:20.148 [info] [chat fetch] engine https://api.githubcopilot.com/chat
2024-01-19 08:57:20.148 [info] [chat fetch] modelMaxTokenWindow 4096
2024-01-19 08:57:20.148 [info] [chat fetch] chat model gpt-4
2024-01-19 08:57:21.309 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 1160 ms
2024-01-19 08:57:21.762 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-01-19 08:57:21.764 [info] [streamChoices] request done: requestId: [ad1ccb43-18e2-4f27-8d33-764b8e53c6be] responseId: [ad1ccb43-18e2-4f27-8d33-764b8e53c6be] model deployment ID: [x74a4b0e7ace1]
2024-01-19 08:57:21.980 [info] [chat fetch] engine https://api.githubcopilot.com/chat
2024-01-19 08:57:21.980 [info] [chat fetch] modelMaxTokenWindow 8192
2024-01-19 08:57:21.981 [info] [chat fetch] chat model gpt-3.5-turbo
2024-01-19 08:57:22.453 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 472 ms
2024-01-19 08:57:22.454 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-01-19 08:57:22.455 [info] [streamChoices] request done: requestId: [9827fb0e-2d77-4a7e-9e7d-f78f1f72b64d] responseId: [9827fb0e-2d77-4a7e-9e7d-f78f1f72b64d] model deployment ID: [x79f089449d1b]
2024-01-19 08:57:27.570 [info] [extension] TypeError: Cannot read properties of undefined (reading 'split')
    at t.printMessageContent (/Users/alvinycheung/.vscode-insiders/extensions/github.copilot-chat-0.11.1/dist/extension.js:1251:85)
    at /Users/alvinycheung/.vscode-insiders/extensions/github.copilot-chat-0.11.1/dist/extension.js:1245:5254
    at Array.map (<anonymous>)
    at t.logMessages (/Users/alvinycheung/.vscode-insiders/extensions/github.copilot-chat-0.11.1/dist/extension.js:1245:5183)
    at n1._provideResponseWithProgress (/Users/alvinycheung/.vscode-insiders/extensions/github.copilot-chat-0.11.1/dist/extension.js:1256:1173)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at n1.provideResponseWithProgress (/Users/alvinycheung/.vscode-insiders/extensions/github.copilot-chat-0.11.1/dist/extension.js:1254:2086)
    at i.y (/Users/alvinycheung/.vscode-insiders/extensions/github.copilot-chat-0.11.1/dist/extension.js:1266:1022)
    at o.$invokeAgent (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:40531)

```

This is what it looks like 
![image](https://github.com/microsoft/vscode-copilot-release/assets/2053588/a27677f1-d3d7-4612-ba88-f2c68946a9f9)

Steps to Reproduce:

1. Start a new instance of Github Copilot Chat
2. Type anything, it works
3. Type anything, it always gives this "Cannot read properties of undefined (reading 'split')" error

**Comment by lramos15** [comment]
Can you try the pre-release version of the extension? I see you're on insiders

**Comment by David-Ben-Mesecke** [comment]
> Can you try the pre-release version of the extension? I see you're on insiders

That worked for me, the current pre release version does not seam to experience the same bug, at least not for me? If that is not just for me, maybe bump the pre release up to release? Because for me at least, the current release is unusable.

**Comment by anthony-jackman** [comment]
I am seeing the same thing as David.  The pre-release is not showing the issue but the non-pre-release is.

**Comment by ford555** [comment]
installing pre-release-version works for me

**Comment by shandou** [comment]
The same issue happened to me today.

**Comment by jerryan999** [comment]
same problem

**Comment by Txabs** [comment]
same problem

**Comment by szykov** [comment]
on stable this error, on pre-release it also happens.
the issue happens when attaching the reference to the file.
workaround is to create a chat for every call to it.

**Comment by freemaths** [comment]
Also seeing this all the time now. Makes copilot unusable.

**Comment by szykov** [comment]
@freemaths is because pre-release does not attach references to opened file by default. once you do it raises an error again.

**Comment by alvinycheung** [comment]
@lramos15 
> Can you try the pre-release version of the extension? I see you're on insiders

I see that there are a handful of comments in here that report using pre-release helps... But, I've installed pre-release and reloaded vs-code no luck :/

**Comment by anthony-jackman** [comment]
Serco Business

Pre-release version works fine.  It is the non prerelease version that has the problem.  I checked again this morning and issue is still there.
Respectfully,
Anthony Jackman
Serco Inc.,
EnergeticPixels LLC.,

From: Alvin Cheung ***@***.***>
Sent: Monday, January 22, 2024 9:57 AM
To: microsoft/vscode-copilot-release ***@***.***>
Cc: Jackman, Anthony, Q (Serco NA) ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/vscode-copilot-release] Cannot read properties of undefined (reading 'split') (Issue #761)

⚠️
WARNING
STOP: Do you recognize this sender?
This email originated from outside of the organization and should be treated with EXTREME CAUTION.
DO NOT click links or open attachments unless you are ABSOLUTELY CERTAIN the contents are safe.
Not sure? Forward this email to ***@***.******@***.***>.
⚠️
WARNING

@lramos15<https://secure-web.cisco.com/1i5ZHP07J_syo-HXYzhnjUseoNdw1Lj6bHYPI8YODANurRO4GcFSMfFudrLB99ICzu7eGGi60MmoWcMqwjzwJ8wjyAb4edfD93QFi-U8jhFq2SgPdGECZ016HQiVVoMVlFr65AcV13Z4y7NcR9MDkOgYL035_Xwli5KDtK6sdwOTz4EtRtducdEQoKMY_SXOcy2OIk2QVSNVv4jOxbdcbJFl_blfwRM1olepmaap9ZbzZS9ey-xECubL1gxgfaCqpU2kwCasNlVkx5OLS-nNJzTStGNu31y69mxzJ3Ugot1FEsBJnZSEQMK_vV91lnPT0/https%3A%2F%2Fgithub.com%2Flramos15>

Can you try the pre-release version of the extension? I see you're on insiders

I see that there are a handful of comments in here that report using pre-release helps... But, I've installed pre-release and reloaded vs-code no luck :/

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/16uLob_IRiRcQm2KkzgGZX0J3JjfSl5FM1lGh19Q78iO4Thb4DY15jqBSltgd7dKS3pKpc7jsc-xiHfp6s59sqpH_2LT1T_Boorxk71Q9Wnybwj2gESefBfuKUD5Ccxlf-tnaWfITu2_LbNL3ZZ0-AcSM-izmOhNO3RztAtDU9ukOKnnekrFN_91pnXxruXxTz26e2cQgX86SXre8Xz-rw-Jmn4QanSaguh2OowbGiEZKgRoPag_MVUkc-Wd7hLIB8H9nQv9h1ICfsSKvPZoKAod6_pgB3_RAzIZIOPX0H-dCWUG3LPn75odRgg6jCfG4/https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode-copilot-release%2Fissues%2F761%23issuecomment-1904303915>, or unsubscribe<https://secure-web.cisco.com/1kpKfyD7U_jenQBTD3FKc9jZcaqH57IrD1oSz0ADQSDNp4YW-VsAEa0jCwRqcHIW9JxtjHO7QTu05GpJ3J6NJsjdYVhhpGZmb1DSkIesB0aLGUqk3cJjG5978Uierg_gD6K1QvAkjH3vhM45cSKlnDGsNAD6osK6iaZ1hnUsnUD-eLV5jCYFJrm11nHjOVaIcBbljdT8S7g-Hne_3TIexDPHLCyX-FKy_qg3LOKYE-OFQ73UF0tUhmcI9qhNhSl9HhHF8Oyko9uFdyMbXsVqHkb_QwY0UzkmYFFa9J71B3ShTZO1-uf62kVOQqiCNUUSJ/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANUEJFXPBA7Q2A2CAZNMMODYP2D5JAVCNFSM6AAAAABCCCVTHWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMBUGMYDGOJRGU>.
You are receiving this because you commented.Message ID: ***@***.******@***.***>>

This e-mail and any attachments are for the intended recipient(s) only and may contain proprietary, confidential material. If you are not the intended recipient, (even if the email address above is yours) do not use, retain, copy or disclose any part of this communication or any attachment as it is strictly prohibited and may be unlawful. If you believe that you have received this e-mail in error, please notify the sender immediately and permanently delete. This email may be a personal communication from the sender and as such does not represent the views of the company. Thank you.

**Comment by ford555** [comment]
Pre-release works for me

**Comment by szykov** [comment]
yeap, also confirm. The pre-release is working now.

**Comment by Eldrick19** [comment]
+1 here. Pre release works but this is a bug in the commercial version

**Comment by lramos15** [comment]
I would like to clarify that the stable version of Copilot Chat is not meant to be mixed with the insiders version of VS Code and the pre-release version of Copilot Chat is not meant to be mixed with the stable version of VS Code. The insiders channel is meant for iterating quickly before we meant a new release so it's likely things will break. If you want a 100% stable experience I recommend the stable version of the Copilot Chat extension + Stable VS Code (blue icon). If you want cutting edge features with an occasional break here and there you want the pre-release of Copilot Chat + Insiders VS Code (green icon)

**Comment by anthony-jackman** [comment]
[like]  Jackman, Anthony, Q (Serco NA) reacted to your message:
________________________________
From: Logan Ramos ***@***.***>
Sent: Monday, January 22, 2024 9:22:16 PM
To: microsoft/vscode-copilot-release ***@***.***>
Cc: Jackman, Anthony, Q (Serco NA) ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/vscode-copilot-release] Cannot read properties of undefined (reading 'split') (Issue #761)

⚠️
WARNING
STOP: Do you recognize this sender?
This email originated from outside of the organization and should be treated with EXTREME CAUTION.
DO NOT click links or open attachments unless you are ABSOLUTELY CERTAIN the contents are safe.
Not sure? Forward this email to ***@***.***
⚠️
WARNING

I would like to clarify that the stable version of Copilot Chat is not meant to be mixed with the insiders version of VS Code and the pre-release version of Copilot Chat is not meant to be mixed with the stable version of VS Code. The insiders channel is meant for iterating quickly before we meant a new release so it's likely things will break. If you want a 100% stable experience I recommend the stable version of the Copilot Chat extension + Stable VS Code (blue icon). If you want cutting edge features with an occasional break here and there you want the pre-release of Copilot Chat + Insiders VS Code (green icon)

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1CAnSCRXXgkNBx4P4v_RmtW5NaePpEUI1rltVFMHawWoWxtrnrqSNgKlPMdckNV8yV4fd7m_LHSuTFxzBfLa1JeF5DgdjgVFiCGrKJxZXRoFff8AgfLzt1C8-CewGBfxVU6FZOsfhZAt1vu5uo-JJFcSrxLbks2AuUzEzfNj0uLcmuSD5HTIbsI-KNf_6Tz0XpAOVJUVe6WHxDae31Kf-CXa9CRk7haGXjVKcdd3P0UFrTN9Q5Fje2Sk74pYz4JIxwWkl2VjyQnzUn5jsElibc33LuzaiQEcOjHF-1Tx_Mk-I3Lbv4iomNzmVrrDN4Ho568_RSkNaPHqy_mF313AeEw/https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode-copilot-release%2Fissues%2F761%23issuecomment-1904840694>, or unsubscribe<https://secure-web.cisco.com/1JX8K4jaDwVZ2LYfHJjyuwpcFv9rU1uO6yg5l3v7EFKxAaVu0LE1NZswOjKLsjgSb3nHy8jP4D6Gj5dcPB4kjV4jn84QdMt7W0usLyVr0ivl_xoUC4UIeHL3M8kZG_c7AQBtba5F2PFFsU3S9WdIfa5SmDATZxTrV9kuuYyFy3egsaYIs4Z8A5mK6quNGIo8LAQHH9FB9FX9DbCNjLaIscu4rSAlPTuawykdBHBk2UxiKpyFznlxKYfgPzSeCKUzu9vQaIBhVepoEJ8g5Z_9e4fys6c4MU9gUeGsjug1RCZDIMK6rLrPPY4x-XJ2Dzq3zmdWz1Qc46VqO2rX_DPI0vA/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANUEJFXT5SEIUXCLJWQ24WDYP3KARAVCNFSM6AAAAABCCCVTHWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMBUHA2DANRZGQ>.
You are receiving this because you commented.Message ID: ***@***.***>

This e-mail and any attachments are for the intended recipient(s) only and may contain proprietary, confidential material. If you are not the intended recipient, (even if the email address above is yours) do not use, retain, copy or disclose any part of this communication or any attachment as it is strictly prohibited and may be unlawful. If you believe that you have received this e-mail in error, please notify the sender immediately and permanently delete. This email may be a personal communication from the sender and as such does not represent the views of the company. Thank you.

**Comment by roblourens** [comment]
Sorry for the trouble all, but we have to make breaking changes between the extension and VS Code, so only pre-release is guaranteed to be compatible with Insiders. You should get pre-release by default when you install Copilot Chat in Insiders, but we can't prevent you from installing stable (which will usually work fine, but not always).

**Comment by WillsB3** [comment]
I'm seeing this error today in VSCode stable.

```
Version: 1.86.0
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:29:11.933Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.0.0
```
