### ISSUE TITLE
Github Copilot Chat wants to sign in using github no matter what

### ISSUE THREAD

**Issue by akshaal** [microsoft/vscode-copilot-release#813]
- VS Code Version: 1.86

Steps to Reproduce:

1. Open a private repository
2. Observe: The extension 'Github Copilot Chat' wants to sign in using Github. We need more permissions to work with this type of repository.
3. Click "Cancel"
4. Restart vscode.
5. Goto step 2.

The extension should remember my choice. I don't really understand why I should give github copilot chat every  possible permission to every single private repository I use. Neither it might be possible for some organizations due to policies.

**Comment by isaachinman** [comment]
Also seeing this. Getting requests for additional permissions to edit GitHub workflow files every few minutes.

**Comment by TylerLeonhardt** [comment]
We need the extra permissions (`repo`) in order to use a GitHub Search API because without it, it says the repo doesn't exist. GitHub doesn't split up `repo` permissions into read and write for this, unfortunately so we ask for the scope required to do the job.

We're asking for similar things to what the GitHub Pull Request & GitHub Repositories extension are asking for. Both extensions which our team owns.

You only need to approve of the additional permissions once, and then you shouldn't need to see it again. Trust me, if GitHub _OAuth_ apps had a way to be more granular we'd take that approach, but the platform doesn't have it.

**Comment by joenap** [comment]
Since when does Microsoft ask for permissions? About to get unsubscribed.

**Comment by vladshcherbin** [comment]
Jesus Christ, this is annoying. Every vscode restart gives this dialog box and you can't even disable this Chat in extensions or via any setting 🤮

**Comment by isaachinman** [comment]
@TylerLeonhardt @Tyriar Do we have any estimate for when this will be fixed?

We are paying users and expect a functional product. Bugs happen but this should be patched ASAP.

**Comment by dawidpstrak** [comment]
This is too wide permissions you require imo

**Comment by TylerLeonhardt** [comment]
I am going to change this to not show a modal every time. You'll see it once and then future reloads will not show it and instead it'll be asked for in the account menu no longer in the forefront.

**Comment by timbo-desosa-overhaul** [comment]
I got the prompt to allow access to this repo but I refused because the organization looks super suspicious? https://github.com/Visual-Studio-Code

I do see that @TylerLeonhardt is a contributor and also responding here so I guess it is legitimate, but it would be less scary if there were actually part of the microsoft org or had some content on a microsoft site verifying that it's legit.

Thanks!

**Comment by TylerLeonhardt** [comment]
![image](https://github.com/microsoft/vscode-copilot-release/assets/2644648/6a573a34-ef87-4a99-9db1-f9d7031398e7)

@timbo-desosa-overhaul do you see the "Part of Microsoft Open Source" and that it's "verified"? We can't use the Microsoft org, it's not really reserved for our use cases and is very very locked down. I could add a README.

**Comment by shanewazabbas** [comment]
> We need the extra permissions (repo) in order to use a GitHub Search API because without it, it says the repo doesn't exist.

But why is this an issue now

**Comment by shanewazabbas** [comment]
> we wanted users to take advantage of this in @workspace queries for a better experience

If thats the case, can this just be locked under a setting to enable/disable it. I don't think its a blocker of a requirement for copilot to function, if I understand it correctly.

**Comment by TylerLeonhardt** [comment]
In prerelease, we now check if you have Chat enabled. Better than a setting.

**Comment by vladshcherbin** [comment]
<img width="268" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/6711845/a708b7ab-3e3d-4444-8e23-6534ca4a9a3e">

HOW TO REMOVE THIS????????????????

I've switched to Pre-Release versions

copilot - v1.160.706 (pre-release)
chat - v0.13.2024020201 (pre-release)

It's up for 2 weeks, I've probably closed this f modal more than 100 times

@TylerLeonhardt when or why it's not released/working???

**Comment by TylerLeonhardt** [comment]
@vladshcherbin do you or your organization have access to chat?

**Comment by Javier-Machin** [comment]
This is still a problem, as it seems it's not possible to install or enable only copilot without chat coming along, therefore the modal keeps appearing. Also I noticed that it works without the permissions, so I don't get why are you not asking for that once the relevant or the related feature that needs it is used, instead of across the board for everybody... 
There has to be a better way than closing the issue and leaving it in the annoying state it is now

**Comment by TylerLeonhardt** [comment]
We're being eager here because there are features that will start using these faster search APIs that may not have such a clear user interaction. In other words, we ask for this upfront before you get in the groove of coding, rather than a modal coming out of nowhere for some future feature that needs this.

I'm letting you know that for now, the extension _can_ work without the additional permissions, but it's slower, and eventually, the extension _will not work without this_.

If you _don't_ actually have chat enabled for your account and you're still seeing this issue **on version 0.12.2 or the latest prerelease** of Copilot Chat, _then a bug remains_ that I need to fix.

If you _do_ have chat enabled for your account, and you're **on the latest prerelease** of Copilot Chat the experience you should see is that you see the modal _once_ and then future reloads of the window should only ask you in the account menu.

If you _do_ have chat enabled for your account, and you're **on version 0.12.2** you'll have the new behavior (only showing 1 modal) when 0.13.0 is released in 2 weeks.

As I stated above, we're talking about a GitHub extension asking for a token to do things with GitHub APIs. It's GitHub talking to GitHub.

**Comment by ayaankazerouni** [comment]
> I'm letting you know that for now, the extension can work without the additional permissions, but it's slower, and eventually, the extension will not work without this.

Should we not use Copilot if we're not prepared to allow read/write permissions to our public and private repos?

**Comment by akshaal** [comment]
> I'm letting you know that for now, the extension _can_ work without the additional permissions, but it's slower, and eventually, the extension _will not work without this_.

@TylerLeonhardt thank you for taking the time participating in the discussion. Just to double check I read it correctly. Does what you say really mean that the copilot will eventually refuse to assist with files that doesn't belong to a github repository? Like now I can simply do:

  touch /tmp/x.sh && code /tmp/x.sh

and then ask copilot chat extension to help me with the script.  Or I could download a tgz file with some source code, extract it to a directory, open that directory in the vscode and ask "@workspace what programming languages are used in the workspace?", and it gives me a useful answer that takes into account content of the files in the workspace - it just works, I've tested it now.

So, are you saying I will no longer be able to use copilot chat in the given scenarios? If the answer is 'yes - it will no longer work', then it's really a sad twist in the story... If 'no - it still will work without a github repository for the workspace' - then maybe you could reuse the same repositoryless strategy as a fallback for the case when the user doesn't want to or just can't grant the RW-token.

**Comment by crahan** [comment]
I've been trying to disable Copilot Chat after this recent permission update change, but I seem to be missing something. I have a GitHub Copilot Individual subscription and Copilot settings on GitHub don't appear to include an option to disable chat (like Organizations have).

If I uninstall the GitHub Copilot Chat extension, then the GitHub Copilot extension itself is uninstalled as well. If I disable the GitHub Copilot Chat extension, then the GitHub Copilot extension is disabled as well.

Can anyone shed some light on how the chat component can be disabled without uninstalling or disabling the GitHub Copilot extension as well?

**Comment by aaronclong** [comment]
Yeah, I'm getting this as well, but I only use this for work and it wants access to my person repos:

> The extension 'GitHub Copilot Chat' wants to sign in using GitHub.
> We need more permissions to work with this type of repository

@TylerLeonhardt  I don't think this is sufficient. I don't want to give CoPilot access to my private repos when I only use it for work

https://github.com/microsoft/vscode-copilot-release/issues/813#issuecomment-1930673126

**Comment by ash47** [comment]
This just started to affect me now, i am getting pop ups now, i use copilot everyday and today is the first day i've seen these modals, and I too don't really want to grant permissions for it to hit all my stuff when it worked fine before without it :(

**Comment by jtc1246** [comment]
This is a very stupid design, and I don't what the developers think. If I cancel, I can still use normally, but it will show every time I open a directory, and need to close manually each time. I am worried that the university can see my usage of copilot if I allow this, because they prohibit the usage of AI in homework and project.

<img width="300" alt="Screenshot 2024-02-22 at 23 55 25" src="https://github.com/microsoft/vscode-copilot-release/assets/43341500/e5d77095-eb02-4d79-9c76-8391342b5bac">

**Comment by jtc1246** [comment]
Can be resolved by following:

Don't use github.com in url, use IP or setup a port forwarding server to github.com (I have only tested using IP, port forwarding server not tested).
For example, if originally you use `git clone git@github.com:aaa/bbbb.git`, use `git clone git@140.82.114.3:aaa/bbbb.git` instead.
The popup window will not show if doing like this.

**Comment by j-rahman** [comment]
I just encountered the same issue. I do not want to give unnecessary read/write access to my public and private repos just to be able to use Copilot. This is bad design, and should be fixed. Why is this active issue marked as "closed"?

**Comment by seanbhart** [comment]
yikes. this is certainly not a closed issue.

![image](https://github.com/microsoft/vscode-copilot-release/assets/10830846/69d21b1b-4e1a-47a2-ad9c-ef3b4b583cef)

**Comment by notpeter** [comment]
@TylerLeonhardt I see that (in prerelease) you've fixed the persistence of this prompt (thanks). Are there other GH issues for the other outstanding concerns?

Specifically, many of us are surprised by:

> We need the extra permissions (repo) in order to use a GitHub Search API because without it, it says the repo doesn't exist. GitHub doesn't split up repo permissions into read and write for this, unfortunately so we ask for the scope required to do the job.

The [documentation for search/code](https://docs.github.com/en/rest/search/search?apiVersion=2022-11-28#search-code--fine-grained-access-tokens) makes no mention of such a limitation and claims to support scoped tokens. Is there an issue elsewhere we should be advocating for?

If you consider this issue (the aggressive prompting) closed, should I start a new issue to specifically discuss the over-scoped permissions request?

**Comment by ash47** [comment]
For me, it still pops up for every VS Code instance, and it takes long
enough where I can be typing, hit enter for a new line right as it pops up
and takes me to GitHub to auth.

Saying no isn't persistent.

**Comment by joshuatshaffer** [comment]
I managed to get this to stop by going to the GitHub Copilot Chat extension and selecting "Install Another Version..." and then choosing `0.11.1`. That version does not have this bug.

**Comment by vladshcherbin** [comment]
Holy moly, after 3 weeks of everyday endless closing of modal window it's finally fixed for me with the latest vscode and copilot releases:

vscode: Version: 1.87.0 (Universal)
copilot: v1.168.741 (pre-release)
copilot chat: v0.13.2024022301 (pre-release)

To everyone subscribed - maybe it'll also fix it for you, give a try 🙌

**Comment by MattiPaivike** [comment]
Really? READ/WRITE access to ALL public and pivate repositories? Do you think it is good practice to "teach" beginner vscode/github users to give extensions these kind of privileges? This should have been an optional setting that the user can activate via a menu, not a popup that shows up every start of vscode. I was finally able to make it stop asking after installing pre-release versions of copilot and copilot chat..

**Comment by crahan** [comment]
Can't the GitHub Copilot extension be decoupled from the GitHub Copilot Chat extension? I don't need chat, I just need the functionality that GitHub Copilot provides.

Yet it's impossible to uninstall or disable the Copilot Chat extension without the Copilot extension also being uninstalled or disabled.

**Comment by akshaal** [comment]
This issue is marked as closed. I think a new issues needs to be created to get some attention to the problems raised in the discussion.

**Comment by aaronclong** [comment]
I opened a new issue for the Scope repo/org access: https://github.com/microsoft/vscode-copilot-release/issues/982

**Comment by bntzio** [comment]
Why is this closed? The issue hasn't been fixed yet...

**Comment by xieshuaix** [comment]
You could persist github login but not github copilot? I just don't get it.

**Comment by keivanpourzang** [comment]
my copilot chat extension no matter how many times I have logged in was ignoring the authentication, I have switched to older version and it fixed (v0.17.1)
