### ISSUE TITLE
'Responsible AI' filtering despite (1) settings allowing matching public code (2) it shouldn't even be triggered by what I asked

### ISSUE THREAD

**Issue by DKchemistry** [microsoft/vscode-copilot-release#839]
This is new as of the update. 

Issue:
<img width="835" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/81147591/e8e37897-d92f-4192-b93f-3f3ba3f74727">
My settings: 

<img width="1222" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/81147591/bacf9f00-fed1-46ee-b684-901090ce53ac">

- VS Code Version: Version: 1.86.0 (Universal)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:29:15.765Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.3.0
- OS Version: Sonoma 14.3
- Logs: See image. 

Steps to Reproduce:

1. You can see it in the image.

**Comment by siblount** [comment]
This issue has also effected me to. 
- VS Code Version: 1.86.2 (user setup)
- OS Version: 10.0.22631 Build 22631
- Logs:[VSCodeLogs.txt](https://github.com/microsoft/vscode-copilot-release/files/14319819/VSCodeLogs.txt)


I asked the chat to help me figure out why a test is failing due to UnauthorizedAccessException. It might've thought that I was trying to delete the `C:\` drive or something. I don't know. I then hinted that it was most likely due to the file is in use but It shouldn't be.

Steps to reproduce:
1) Create a new chat

2) Because I use the `#file` multiple times, here are the files at the time of use:
[Github Permalink: DPDatabaseTests.cs](https://github.com/siblount/PMForDAZ/blob/ae2dc4706ee074935b664a5b1078d586e4d72abf/src/DAZ_Installer.DatabaseTests/DPDatabaseTests.cs#L877C9-L901C10)
[Github Permalink: DPDatabase.Public.cs](https://github.com/siblount/PMForDAZ/blob/ae2dc4706ee074935b664a5b1078d586e4d72abf/src/DAZ_Installer.Database/DPDatabase.Public.cs#L94-L113)
[Github Permalink: DPDatabase.cs](https://github.com/siblount/PMForDAZ/blob/ae2dc4706ee074935b664a5b1078d586e4d72abf/src/DAZ_Installer.Database/DPDatabase.cs#L723C1-L756C10)

3) Look at the chat history from your side.
