### ISSUE TITLE
GCC cannot use your files as reference anymore, and denies it ever could

### ISSUE THREAD

**Issue by mnihl** [microsoft/vscode-copilot-release#841]
- VS Code Version: 1.86.0 (user setup)
Date: 2024-01-31T10:28:19.990Z
OS: Windows_NT x64 10.0.22631
- Logs: Can't you view the current file I have open?
- I'm sorry for any confusion, but as an AI, I don't have the ability to directly view or access the files on your computer or in your development environment. I can provide assistance based on the information you provide to me. If you're having trouble with a specific piece of code, feel free to share the code or describe the issue in detail, and I'll do my best to help you resolve it.
- I was just prompting you and you used my files as references?
- I apologize for any confusion, but as an AI developed by OpenAI, I don't have the ability to access or view your files. I can provide assistance based on the information you provide to me. If you're having trouble with a specific piece of code, feel free to share the code or describe the issue in detail, and I'll do my best to help you resolve it.
- Is this inability to access and view my files a new feature in the recent update to your software?
- As an AI developed by OpenAI, I've never had the ability to access or view your files. This is not a new feature or a recent change, but a fundamental aspect of how I operate. I'm designed to respect user privacy and confidentiality. I can only provide assistance based on the information you explicitly provide during our conversation.

Steps to Reproduce:

1. Try asking GCC any question about your open code file

It was working as intended and then as I updated and restarted VScode for latest Github Copilot Chat version it started denying it oculd ever use files as referenes.

**Comment by hjain-spcg** [comment]
this is totally broken now -- so annoying.

**Comment by StephaneKazmierczak** [comment]
same problem for me, it was working previously, but not anymore in the new pre release

**Comment by joeltheai** [comment]
yeah same problem for me. But it worked in codespaces but not locally in vscode. The reference only works if i have selected the lines from the file.

**Comment by joeltheai** [comment]
ok it works now. I switched "copilot chat"  version to the pre-release version. ver 12 to 13. I think version 12 was messing it up.

**Comment by mnihl** [comment]
> ok it works now. I switched "copilot chat" version to the pre-release version. ver 12 to 13. I think version 12 was messing it up.

This did not solve the issue for me. Same problem remains where yes, I can highlight code snippets and it can reference those. But it cannot reference the file you are currently viewing for a more holistic question.

**Comment by Alban-V** [comment]
Seriously, we paid for it and it's completely broken ...

**Comment by jmineau** [comment]
You need to use `#editor`

Duplicate of #827 

See https://code.visualstudio.com/updates/v1_86#_default-context-in-chat

**Comment by simoncpu** [comment]
I thought it was only me. Same problem here.

**Comment by tino-kreowsky** [comment]
I have the same problems since the latest VSC update. Now copilot doesn't check any files in my vsc explorer anymore and commands like @workspace don't look at the files either. Now copilot only looks at the content of a file when I explicitly open the file and use the #editor command in my chat message which is not the behaviour it had before and not the way i want it.

For example before the upate i could just ask in the copilot chat where the login for users is handled and it would go through all the files in the project from the vsc explorer and then list the files where it is handled and then i could even ask for the specific lines in the files. Now it just keeps telling me the same message that it can't access files and that i have to use the vsc search function myself to look for specific things with generic suggestions like "Use CTRL + F and search for login" which isn't helpful at all.

**Comment by kennyjacobson** [comment]
Same problem as everyone else.

**Comment by roblourens** [comment]
Yes see https://github.com/microsoft/vscode-copilot-release/issues/827
