### ISSUE TITLE
Copilot doesn't resolve workspace

### ISSUE THREAD

**Issue by salientknight** [microsoft/vscode-copilot-release#861]
GitHub Copilot v1.157.695 (pre-release)
- VS Code Version:
Version: 1.87.0-insider (Universal)
Commit: 9db1b0571e119289a2264971bdac75793965e063
Date: 2024-02-07T05:48:09.043Z (11 hrs ago)
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0
- OS Version: Sanoma 14.2.1
- Logs: None

Steps to Reproduce:

1. use @workspace option in chat
![Screenshot 2024-02-07 at 11 44 54 AM](https://github.com/microsoft/vscode-copilot-release/assets/40220684/3e32ac89-898c-4901-84cf-88d05e967f73)

Copilot doesn't resolve the workspace as per image

**Comment by mjbvz** [comment]
Please test this again with the latest builds. We've fixed a number of issues since this was opened

Workspace questions may still take some time in a few case:

- Very slow or unreliable network connection
- You have a very large workspace that is not backed by a github repo. In these cases we try to build up a local index which can be somewhat slow. You can try excluding some files using the `search.exclude` setting
