### ISSUE TITLE
[C++] `@workspace /explain` is collecting a single reference and missing important references for a proper answer

### ISSUE THREAD

**Issue by lukka** [microsoft/vscode-copilot-release#868]
- VS Code Version: 1.87-insider-2024-02-06` (`cf7ddbb51`)
- OS Version:  Windows 11 23H2

@isidorn @joyceerhl the problem reported here [was mentioned in this other issue,](https://github.com/microsoft/vscode-copilot-release/issues/780#issuecomment-1930585072) creating a new entry here so that it does not get lost.

## Summary: 

@joyceerhl I can't see any interaction with the C++ language service when using the `@workspace /explain` subcommand, and only one reference is ever used in the answer, which is the file where the selection occurs. On the other hand, I'd expect Copilot Chat asking the language service for symbol declaration/definition/references to correctly create the set of references.

_Please feel free to ping me anytime to help with repro step or with debugging anything on the C++ Lang Service side._

## Here the details

- I installed the prereleases of [CMake Tools](https://github.com/microsoft/vscode-cmake-tools), [C++](https://github.com/microsoft/vscode-cpptools), CopilotChat `v0.13.2024020601` and VSCode `1.87-insider-2024-02-06` (`cf7ddbb51`).
- Checkout the [CMake code base](https://github.com/Kitware/CMake), configured with CMake and built it.
- then I asked the following two questions below.

### Two examples of the problem

@joyceerhl in the next screenshot there are two questions asked that, to being properly answered, they need the context from other files than the one where the selection is done: the problem is that I do not see Copilot Chat leveraging the C++ Language Service for finding references of the `ComputeDefines` member function, which would have been fundamental to answer both questions:

![image](https://github.com/microsoft/vscode-copilot-release/assets/681992/bf1552ed-0dd0-4d68-af92-240e43becb2c)

The only reference used is the selection I've done at `Source\cmNinjaTargetGenerator.h` lines 99:102, and I would expect to see at least the file `Source\cmNinjaTargetGenerator.cxx` referenced, which would be needed to answer the second question.

**Comment by joyceerhl** [comment]
Hi @lukka, from what I can tell there are three parts to this issue:
1. I have a PR in the Copilot Chat extension to recognize more C++ language features (in this case, we were missing the `function_declarator` node type). This fix will be in tomorrow's pre-release, and will allow you to highlight just the symbol name `ComputeDefines` and get the corresponding definition included.
2. With the fix for part 1, I debugged the Copilot Chat extension with Code-OSS and the C++ extension, and it looks like the C++ language server does not provide definitions that are requested via the `vscode.executeDefinitionProvider` API command for the file `cmNinjaTargetGenerator.h` and ext host position `[100, 14]` when there is a selection in the active editor that includes a symbol of interest _and the cursor is not currently on that symbol_. This is the scenario that your second question in the screenshot above shows, since the selection spans multiple lines. I believe this may need to be addressed in the C++ language server.
3. We do not currently include symbol references for any symbols in `/explain`. This is the scenario that your first question in the screenshot above shows. This is a feature request that we are already tracking separately, and this work would happen for all languages together.

**Comment by joyceerhl** [comment]
Verification steps (requires tomorrow's pre-release)
1. Clone https://github.com/Kitware/CMake
2. Have C++ extension pack installed and configured for the project
3. Put your cursor on `ComputeDefines` https://github.com/Kitware/CMake/blob/026270fe3d86deb6ccb652e95be3b79f01b5c30a/Source/cmNinjaTargetGenerator.h#L101-L102
4. Type `@workspace /explain` into chat and hit enter
5. Ensure that the definitions for `ComputeDefines` are included (there should be 3 references used)

**Comment by meganrogge** [comment]
@joyceerhl I don't see any references used but the definitions look correct.

![Image](https://github.com/microsoft/vscode-copilot-release/assets/29464607/0e2a86c9-7427-4c41-a370-2fb6c5e99a04)

**Comment by meganrogge** [comment]
same when I run view in chat

![Image](https://github.com/microsoft/vscode-copilot-release/assets/29464607/6eb75e27-5e02-4713-82cc-e95c79786ba2)

**Comment by lukka** [comment]
@joyceerhl I tested with CopilotChat `v0.13.2024022301` and `C++` v1.19.4, and the result looks really good (thank you!):
- the declaration and definition of `ComputeDefines` are available in the two references. @joyceerhl what would be the third reference you mentioned?
- the labeling system is also working, looking into the Output pane where it says "a project of the following nature: cpp, cmake".

<img width="819" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/681992/755f3f39-0025-412e-b9c4-826af7f2e9be">

@meganrogge in your test, are you using configuring the project with CMake? That is necessary to enable C++ IntelliSense, which is then used by Copilot Chat to get the references. Otherwise, if C++ IntelliSense is not enabled on the project, you won't get references indeed. To configure the project, run the `CMake: Configure` command from the command palette. it can take some time, and it requires to have a C++ compiler installed (e.g. Visual Studio MSVC).
