### ISSUE TITLE
[C++] `@workspace` agent is splitting C++ source code in improper chunks

### ISSUE THREAD

**Issue by lukka** [microsoft/vscode-copilot-release#869]
- VS Code Version: 1.87-insider-2024-02-06` (`cf7ddbb51`)
- OS Version:  Windows 11 23H2

@isidorn @sbatten @mjbvz the problem reported here [was mentioned in this other issue,](https://github.com/microsoft/vscode-copilot-release/issues/780#issuecomment-1930585072), creating a new entry here so that it does not get lost.

## Summary

@mjbvz [as you asked previously](https://github.com/microsoft/vscode-copilot-release/issues/780#issuecomment-1908637804), while `@workspace` is doing a great job at collecting references in a C++ code base, it looks like the references' content is improperly split in chuncks.

_Please feel free to ping me anytime to help with repro step or with debugging anything on the C++ Lang Service side._

## Here the details

- I installed the prereleases of [CMake Tools](https://github.com/microsoft/vscode-cmake-tools), [C++](https://github.com/microsoft/vscode-cpptools), CopilotChat `v0.13.2024020601` and VSCode `1.87-insider-2024-02-06` (`cf7ddbb51`).
- Checkout the [CMake code base](https://github.com/Kitware/CMake), configured with CMake and built it.
- then I asked the following two questions below.

### A sample of the experienced problem

@mjbvz  in the next screenshot, the answer to the question is very well constructed, especially because there are 8 references being collected and used, especially the file `Source\cmNinjaTargetGenerator.cxx` which contains the key to a proper answer.

![image](https://github.com/microsoft/vscode-copilot-release/assets/681992/d5b3d4e7-4f22-4063-8a5a-0589c3b6c04b)

As you [asked before](https://github.com/microsoft/vscode-copilot-release/issues/780#issuecomment-1908637804), the portion of text from each reference is not as I would expect, going up to the end of a function definition for example, but they are just terminating in the middle of anything.

For example:

- This is just a blank line:
    ![image](https://github.com/microsoft/vscode-copilot-release/assets/681992/9d83a944-34e0-4271-89c5-10519a0bf5d5)

- These are not going up to the end of the function body:
    ![image](https://github.com/microsoft/vscode-copilot-release/assets/681992/7086c9a4-2b10-4db2-a3e6-8c1c7f2ef654)
    ![image](https://github.com/microsoft/vscode-copilot-release/assets/681992/5d9596d0-3ba0-4644-b171-cf9c3a82aed7)
    ![image](https://github.com/microsoft/vscode-copilot-release/assets/681992/b800da08-c952-47a4-9004-eba0cc3ac62f)

**Comment by andreamah** [comment]
Are you still able to get the same chunks? I just tried with the latest prerelease and got the following:

<img width="350" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/31675041/71cdaa20-7b07-4f64-b470-599f300d393f">

That being said, I still get this chunk:
<img width="672" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/31675041/d12abbc3-8772-4282-be80-5666db58171d">

This is just because we limit the number of tokens per chunk that we can send to the model due to the limited context window size. This is one of the more unfortunate examples of how it cuts off chunks (in addition to the other one that cuts off the ending braces, I believe). 

In respect to the one that only captured the function header and the one that is just one line, those are definitely strange and problematic. There should have been some minor fixes to how chunking works, so perhaps these were fixed as a byproduct. If you're able to reproduce the chunks on the latest prerelease, please list your query here with `Github Copilot Chat` logs in the output tab.
