### ISSUE TITLE
Error from provider: Cannot read properties of undefined (reading 'map') getting this on both prerelease and stable version

### ISSUE THREAD

**Issue by fisforfaheem** [microsoft/vscode-copilot-release#895]
it's happening since last 2 days tried every possible solution

**Comment by aiday-mar** [comment]
Hi @fisforfaheem thank you posting. Could you include the stack trace you see in the developer tools from VS Code, because we currently can not track the origin of the issue.

**Comment by Luiz-Ferreira-96** [comment]
I am also getting this error, it occurs when I try to send a second message for copilot. For now, I managed to open a new chat every time that I want to ask something, but it is extremely annoying because this way it makes more difficult to refine the solutions since I cannot iterate trough the solution.

**Comment by JayDeeAU** [comment]
I have the same issue as @Luiz-Ferreira-96. I have to /newChat between every message otherwise I get the same error. I am using VSCode Insider 1.87.0-insider.

**Comment by aiday-mar** [comment]
Hi @Luiz-Ferreira-96, @JayDeeAU thank you for commenting here. In order to route the issue to the correct person, could you include more information as to the error that is happening. To do this, you may toggle the developer tools in VS Code, by selecting the command `Developer: Toggle Developer Tools` from the command palette. This will open the dev tools, from where you can copy paste the stack trace here for us to see the error.

**Comment by fisforfaheem** [comment]
kindly someone give them details..

**Comment by aiday-mar** [comment]
Assigning @roblourens because it appears this error happens in the call to `addHistory`

**Comment by fisforfaheem** [comment]
Also please ask team to fix the context issue, its too small even with
chatgpt 4 being used...whole point of this service becomes useless...it
should have atleast 2000 lines of contexr support
