### ISSUE TITLE
Aggressive rate limiting issues

### ISSUE THREAD

**Issue by binaryfire** [microsoft/vscode-copilot-release#913]
Been hitting this pretty regularly today:

<img width="547" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/5361908/90a994b9-48d9-4ae6-8d7e-7418ed72c8d8">

Quite frustrating for a paid service. It's impossible to spam VS Code chat... It's not a publicly accessible API. It's behind an input field that requires human interaction, plus there's a significant delay between requests because you have to wait for the previous response to be returned. Which means there's already a lot of natural rate limiting going on. So why does it need to be rate limited at all?

This seems like a purely cost-saving measure to me. Please ease up on cutting corners like this.

**Comment by canuckjacq** [comment]
Hm, generally when we see Copilot complaining about rate limits, it's about overall rate limits, and is usually caused by other calls to the API. Copilot doesn't get an exemption from the overall rate limits, and abuse of Copilot is handled with a Copilot specific block rather than rate limiting. 

Please re-check any jobs you may have going that hit the GitHub API to ensure that you have rate limits baked in. You can read more [here](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#about-primary-rate-limits). 

If you don't know what this could be, please open a ticket with GitHub Support who can have a closer look at it for you.

**Comment by binaryfire** [comment]
I don't have anything making calls to the GitHub API.

**Comment by canuckjacq** [comment]
Yup, I'm seeing [a whole bunch of reports of this now.](https://github.com/microsoft/vscode-copilot-release/issues/920) The team is aware!

**Comment by jcgerhard** [comment]
Hello guys, also a paying user with the same issue here! Makes Copilot kind of "unusable" atm! Very annoying!

**Comment by BabyWaffles** [comment]
What the hell is going on with the GitHub co-pilot? I have to constantly wait for at least 5 minutes to clear my rate limit restriction which is extremely annoying and it disrupts my workflow and concentration. I've paid for my subscription and it is still rate-limited, like seriously?

**Comment by roblourens** [comment]
There was a service-side issue which should now be resolved- sorry for the trouble everyone!
