### ISSUE TITLE
Chat editor breaks after switching tabs

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-copilot-release#914]
- Open chat in editor
- Click some other tab like a text file
- Use keyboard shortcut `cmd+shift+]` to switch back to the chat editor tab

`The editor could not be opened due to an unexpected error: Cannot read properties of undefined (reading 'viewState')`

@bpasero @lramos15  my code is here: https://github.com/microsoft/vscode/blob/af8c22960307d58c174fc89f2fa050b0aa683357/src/vs/workbench/contrib/chat/browser/chatEditor.ts#L84-L97

When I click back to the tab, `options` is undefined. This works in stable. Am I doing the wrong thing here or did something change? 

I also put `IChatEditorOptions` on the ChatEditorInput. Not sure I'm using this all right.

**Comment by bpasero** [comment]
I cannot reproduce:

![Recording 2024-02-20 at 07 12 37](https://github.com/microsoft/vscode-copilot-release/assets/900690/3e89a9cb-a506-4cba-afa9-654aeb9f8639)

**Comment by roblourens** [comment]
Oh it only reproes if you switch tabs using the keyboard. I guess I wrote click in the OP. But I realized that this is actually from a change on our side, https://github.com/microsoft/vscode/pull/204534/files. 

Kudos to TS for letting me override `setInput(... options: IEditorOptions | undefined ...)` and omit the ` | undefined`. No problem there at all.

**Comment by roblourens** [comment]
Here's a fix https://github.com/microsoft/vscode/pull/205745 but I don't totally understand this and it's been awhile since I looked at it. Why are there options on the editor input, and also options passed into `setInput`? Are those like override options for the Input's options? Is this logic right?

**Comment by bpasero** [comment]
@roblourens I think your fix is good. editor options are the thing that you can pass into the `IEditorService.openEditor` call and will end up in your `setInput` method. They might be `undefined`, for example when you switch editors with keys as in this case. 

Editor options on the level of the editor input are typically not something you would need to do. But I see how the base `EditorInput.resolve` method seems to get the `EditorOptions` passed in as optional parameter. That is very misleading because its really up to the editor to pass it down or not. https://github.com/microsoft/vscode/pull/205751 removes this as it was not used by most editors anyway.

**Comment by eleanorjboyd** [comment]
tested by switching tabs using the keyboard, works as expected
