### ISSUE TITLE
Adding #files to chat should be easier/faster

### ISSUE THREAD

**Issue by carltonbrown** [microsoft/vscode-copilot-release#971]
A large GitHub Enterprise customer have expressed:

> `#file` references are awkward because they can’t be pasted or derived from open tabs. They require interaction with a modal or a select list.  If I have a collection of say 5 files that are relevant for establishing context, this is painful to achieve. So I can’t paste #file refs into chat and make them turn “blue”.  A `#tabs` would have been more useful.
>
> Basically, it should be possible to get parity with completions.

Another community member has expressed:

>  the announced context variable #file doesn't work. As I wrote, I tried #file context variable (even though not in the screenshot I shared). As expected, it said it referenced the whole file (lines 1-), but still right after it copilot chat said it can't access the file.

**Comment by roblourens** [comment]
The second issue- the file will not be used when it is too large or doesn't fit into the context window. We can do more to compress it, and also it should be obvious whether the file was actually used: https://github.com/microsoft/vscode-copilot-release/issues/926

Will use this issue for the first point

**Comment by joyceerhl** [comment]
Closing as we've made several improvements here over the last few releases:
- You can do multi select of tabs and then drag and drop them into chat to add them as context
- You can also do multi select in the file explorer view and search view to add files as context
- In the file picker you can right arrow to add a file as context without closing the picker
- In Copilot Edits you can click the Add Files button then select Open Editors to add all open editors to your working set

Also, for the second point, we now have larger context windows since a few months ago, so truncation should be less frequent, and there is a warning when part of the file is omitted.
